
// Generated by MyGeneration Version # (1.3.0.3)

using System;
using System.Data.Common;
using System.Data;
using Microsoft.Practices.EnterpriseLibrary.Data;

namespace EquitableGourmet
{
	public class Account : AccountBase
	{
		#region < CONSTRUCTORES >
		
		public Account() : base()	{}
		
		#endregion



        public static DataTable AccountExists(String marigoldnumber)
        {
            Database db = DatabaseFactory.CreateDatabase();
            string sqlCommand = "AccountExists";
            DbCommand dbCommandWrapper = db.GetStoredProcCommand(sqlCommand);
            db.AddInParameter(dbCommandWrapper, "@MarigoldNumber", DbType.String, marigoldnumber);
            DataSet ds = db.ExecuteDataSet(dbCommandWrapper);

            DataTable dt = ds.Tables[0];

            return dt;


        }
	}
}
