/*
'===============================================================================
'  Generated From - CSharp_DAAB_BusinessEntity.vbgen
' 
'  ** IMPORTANT  ** 
'  How to Generate your stored procedures:
' 
'  SQL      = SQL_DAAB_Net2_StoredProcs.vbgen
'  
'  This object is 'abstract' which means you need to inherit from it to be able
'  to instantiate it.  This is very easily done. You can override properties and
'  methods in your derived class, this allows you to regenerate this class at any
'  time and not worry about overwriting custom code. 
'
'  NEVER EDIT THIS FILE.
'
'  public class YourObject :  YourObjectBase
'  {
'
'  }
'
'===============================================================================
*/

// Generated by MyGeneration Version # (1.3.0.3)

using System;
using System.Data;
using System.Configuration;
using System.Collections;
using System.Collections.Specialized;
using System.Xml;
using System.IO;

using Microsoft.Practices.EnterpriseLibrary.Data;
using System.Data.Common;

namespace DL
{
	public abstract class AddressBase
	{
		#region < VARIABLES >
		private int _AddressID;
		private int _CountryID;
		private int _CityID;
		private int _DistrictID;
		private string _Area;
		private string _Street;
		private string _Building;
		private int _AccountID;
		private int _AddressTypeID;
		private bool _Del;
		private bool _isNew;
		#endregion
		
		#region < CONSTRUCTORES >
		protected AddressBase()
		{
			_AddressID = 0;
			_CountryID = 0;
			_CityID = 0;
			_DistrictID = 0;
			_Area = string.Empty;
			_Street = string.Empty;
			_Building = string.Empty;
			_AccountID = 0;
			_AddressTypeID = 0;
			_Del = false;
		}
		
		protected AddressBase(int AddressID) : this()
		{
			_AddressID = AddressID;
		}
	
		protected AddressBase(int AddressID, int CountryID, int CityID, int DistrictID, string Area, string Street, string Building, int AccountID, int AddressTypeID, bool Del) : this()
		{
			_AddressID = AddressID;
			_CountryID = CountryID;
			_CityID = CityID;
			_DistrictID = DistrictID;
			_Area = Area;
			_Street = Street;
			_Building = Building;
			_AccountID = AccountID;
			_AddressTypeID = AddressTypeID;
			_Del = Del;
		}

		#endregion
		
		#region < Metodos para Obtención de Detalles >

		public static DataTable GetByAccount(int AccountID)
		{
			Database db = DatabaseFactory.CreateDatabase();
            string sqlCommand = "Select * From Address Where AccountID = @AccountID";
            DbCommand dbCommandWrapper = db.GetSqlStringCommand(sqlCommand);
			db.AddInParameter(dbCommandWrapper, "@AccountID", DbType.Int32, AccountID);

			DataTable t = db.ExecuteDataSet(dbCommandWrapper).Tables[0];
			
			t.Columns["AccountID"].DefaultValue = AccountID;

            return t;
		}

		public static DataTable GetByAddressType(int AddressTypeID)
		{
			Database db = DatabaseFactory.CreateDatabase();
            string sqlCommand = "Select * From Address Where AddressTypeID = @AddressTypeID";
            DbCommand dbCommandWrapper = db.GetSqlStringCommand(sqlCommand);
			db.AddInParameter(dbCommandWrapper, "@AddressTypeID", DbType.Int32, AddressTypeID);

			DataTable t = db.ExecuteDataSet(dbCommandWrapper).Tables[0];
			
			t.Columns["AddressTypeID"].DefaultValue = AddressTypeID;

            return t;
		}

		public static DataTable GetByCity(int CityID)
		{
			Database db = DatabaseFactory.CreateDatabase();
            string sqlCommand = "Select * From Address Where CityID = @CityID";
            DbCommand dbCommandWrapper = db.GetSqlStringCommand(sqlCommand);
			db.AddInParameter(dbCommandWrapper, "@CityID", DbType.Int32, CityID);

			DataTable t = db.ExecuteDataSet(dbCommandWrapper).Tables[0];
			
			t.Columns["CityID"].DefaultValue = CityID;

            return t;
		}

		public static DataTable GetByCountry(int CountryID)
		{
			Database db = DatabaseFactory.CreateDatabase();
            string sqlCommand = "Select * From Address Where CountryID = @CountryID";
            DbCommand dbCommandWrapper = db.GetSqlStringCommand(sqlCommand);
			db.AddInParameter(dbCommandWrapper, "@CountryID", DbType.Int32, CountryID);

			DataTable t = db.ExecuteDataSet(dbCommandWrapper).Tables[0];
			
			t.Columns["CountryID"].DefaultValue = CountryID;

            return t;
		}

		public static DataTable GetByDistrict(int DistrictID)
		{
			Database db = DatabaseFactory.CreateDatabase();
            string sqlCommand = "Select * From Address Where DistrictID = @DistrictID";
            DbCommand dbCommandWrapper = db.GetSqlStringCommand(sqlCommand);
			db.AddInParameter(dbCommandWrapper, "@DistrictID", DbType.Int32, DistrictID);

			DataTable t = db.ExecuteDataSet(dbCommandWrapper).Tables[0];
			
			t.Columns["DistrictID"].DefaultValue = DistrictID;

            return t;
		}

		#endregion
		
		#region < PROPIEDADES >
		
		public int AddressID
		{
			get	{ return _AddressID; }
			set	{ _AddressID = value; }
		}
		
		public int CountryID
		{
			get	{ return _CountryID; }
			set	{ _CountryID = value; }
		}
		
		public int CityID
		{
			get	{ return _CityID; }
			set	{ _CityID = value; }
		}
		
		public int DistrictID
		{
			get	{ return _DistrictID; }
			set	{ _DistrictID = value; }
		}
		
		public string Area
		{
			get	{ return _Area; }
			set	{ _Area = value; }
		}
		
		public string Street
		{
			get	{ return _Street; }
			set	{ _Street = value; }
		}
		
		public string Building
		{
			get	{ return _Building; }
			set	{ _Building = value; }
		}
		
		public int AccountID
		{
			get	{ return _AccountID; }
			set	{ _AccountID = value; }
		}
		
		public int AddressTypeID
		{
			get	{ return _AddressTypeID; }
			set	{ _AddressTypeID = value; }
		}
		
		public bool Del
		{
			get	{ return _Del; }
			set	{ _Del = value; }
		}
		
		public bool IsNew
		{
			get 
			{ 
				_isNew = (_AddressID == 0);
				return _isNew; 
			}
			set { _isNew = value; }
		}
		#endregion		

		#region Utilerias
		public static bool Existe(int AddressID)
		{
			Database db = DatabaseFactory.CreateDatabase();
			string sqlCommand = "daab_ExistsAddress";
			DbCommand dbCommandWrapper = db.GetStoredProcCommand(sqlCommand);

			// Add in parameters
			db.AddInParameter(dbCommandWrapper, "@AddressID", DbType.Int32, AddressID);

			// DataSet that will hold the returned results		
			// Note: connection closed by ExecuteDataSet method call 
			bool ret = false;
			int num = Convert.ToInt32(db.ExecuteScalar(dbCommandWrapper));
			ret = num > 0;
			return ret;
		}
		
		public static DataTable GetAllAddress()
		{
			Database db = DatabaseFactory.CreateDatabase();

			string sqlCommand = "daab_GetAllAddress";
			DbCommand dbCommandWrapper = db.GetStoredProcCommand(sqlCommand);
			DataTable ret = db.ExecuteDataSet(dbCommandWrapper).Tables[0];
			
            ret.PrimaryKey = new DataColumn[] { ret.Columns["AddressID"] };
			
            return ret;
		}
		
		public static void SaveAll(DataTable tabla)
		{
			Database db = DatabaseFactory.CreateDatabase();
			DbDataAdapter da = db.GetDataAdapter();
			
			da.SelectCommand = db.GetStoredProcCommand("daab_GetAllAddress");
            da.InsertCommand = db.GetStoredProcCommand("daab_AddAddress");
            da.UpdateCommand = db.GetStoredProcCommand("daab_UpdateAddress");
            da.DeleteCommand = db.GetStoredProcCommand("daab_DeleteAddress");
			
			#region Parametros de InsertCommand
			db.AddOutParameter(da.InsertCommand, "@AddressID", DbType.Int32, 4);
			db.AddInParameter(da.InsertCommand, "@CountryID", DbType.Int32, "CountryID", DataRowVersion.Default);
			db.AddInParameter(da.InsertCommand, "@CityID", DbType.Int32, "CityID", DataRowVersion.Default);
			db.AddInParameter(da.InsertCommand, "@DistrictID", DbType.Int32, "DistrictID", DataRowVersion.Default);
			db.AddInParameter(da.InsertCommand, "@Area", DbType.String, "Area", DataRowVersion.Default);
			db.AddInParameter(da.InsertCommand, "@Street", DbType.String, "Street", DataRowVersion.Default);
			db.AddInParameter(da.InsertCommand, "@Building", DbType.String, "Building", DataRowVersion.Default);
			db.AddInParameter(da.InsertCommand, "@AccountID", DbType.Int32, "AccountID", DataRowVersion.Default);
			db.AddInParameter(da.InsertCommand, "@AddressTypeID", DbType.Int32, "AddressTypeID", DataRowVersion.Default);
			db.AddInParameter(da.InsertCommand, "@Del", DbType.Boolean, "Del", DataRowVersion.Default);

			#endregion
			
			#region Parametros de UpdateCommand
			db.AddInParameter(da.UpdateCommand, "@AddressID", DbType.Int32, "AddressID", DataRowVersion.Default);
			db.AddInParameter(da.UpdateCommand, "@CountryID", DbType.Int32, "CountryID", DataRowVersion.Default);
			db.AddInParameter(da.UpdateCommand, "@CityID", DbType.Int32, "CityID", DataRowVersion.Default);
			db.AddInParameter(da.UpdateCommand, "@DistrictID", DbType.Int32, "DistrictID", DataRowVersion.Default);
			db.AddInParameter(da.UpdateCommand, "@Area", DbType.String, "Area", DataRowVersion.Default);
			db.AddInParameter(da.UpdateCommand, "@Street", DbType.String, "Street", DataRowVersion.Default);
			db.AddInParameter(da.UpdateCommand, "@Building", DbType.String, "Building", DataRowVersion.Default);
			db.AddInParameter(da.UpdateCommand, "@AccountID", DbType.Int32, "AccountID", DataRowVersion.Default);
			db.AddInParameter(da.UpdateCommand, "@AddressTypeID", DbType.Int32, "AddressTypeID", DataRowVersion.Default);
			db.AddInParameter(da.UpdateCommand, "@Del", DbType.Boolean, "Del", DataRowVersion.Default);

			#endregion
			
			#region Parametros de DeleteCommand
			db.AddInParameter(da.DeleteCommand, "@AddressID", DbType.Int32, "AddressID", DataRowVersion.Default);

			#endregion

			db.UpdateDataSet(tabla.DataSet, tabla.TableName, da.InsertCommand, da.UpdateCommand, da.DeleteCommand, UpdateBehavior.Standard);
		}
		#endregion

		/// <summary>
		/// Populates a dataset with info from the database, based on the requested primary key.
		/// </summary>
		/// <param name="AddressID"></param>
		/// <returns>A DataSet containing the results of the query</returns>
		private DataSet LoadByPrimaryKey(int AddressID)
		{
			// Create the Database object, using the default database service. The
			// default database service is determined through configuration.
			Database db = DatabaseFactory.CreateDatabase();

			string sqlCommand = "daab_GetAddress";
			DbCommand dbCommandWrapper = db.GetStoredProcCommand(sqlCommand);

			// Add in parameters
			db.AddInParameter(dbCommandWrapper, "@AddressID", DbType.Int32, AddressID);

			// DataSet that will hold the returned results		
			// Note: connection closed by ExecuteDataSet method call 
			return db.ExecuteDataSet(dbCommandWrapper);
		}
	
		/// <summary>
		/// Populates current instance of the object with info from the database, based on the requested primary key.
		/// </summary>
		/// <param name="AddressID"></param>
		public virtual void Load(int AddressID)
		{
			// DataSet that will hold the returned results		
			DataSet ds = this.LoadByPrimaryKey(AddressID);
			
			// Load member variables from datarow
			DataRow row = ds.Tables[0].Rows[0];
			_AddressID = (int)row["AddressID"];
			_CountryID = row.IsNull("CountryID") ? 0 : (int)row["CountryID"];
			_CityID = row.IsNull("CityID") ? 0 : (int)row["CityID"];
			_DistrictID = row.IsNull("DistrictID") ? 0 : (int)row["DistrictID"];
			_Area = row.IsNull("Area") ? string.Empty : (string)row["Area"];
			_Street = row.IsNull("Street") ? string.Empty : (string)row["Street"];
			_Building = row.IsNull("Building") ? string.Empty : (string)row["Building"];
			_AccountID = row.IsNull("AccountID") ? 0 : (int)row["AccountID"];
			_AddressTypeID = row.IsNull("AddressTypeID") ? 0 : (int)row["AddressTypeID"];
			_Del = row.IsNull("Del") ? false : (bool)row["Del"];
		}

		/// <summary>
		/// Adds or updates information in the database depending on the primary key stored in the object instance.
		/// </summary>
		/// <returns>Returns True if saved successfully, False otherwise.</returns>
		public bool Save()
		{
			if (this.IsNew)
				return Insert();
			else
				return Update();
		}

		/// <summary>
		/// Inserts the current instance data into the database.
		/// </summary>
		/// <returns>Returns True if saved successfully, False otherwise.</returns>
		private bool Insert()
		{
			// Create the Database object, using the default database service. The
			// default database service is determined through configuration.
			Database db = DatabaseFactory.CreateDatabase();

			string sqlCommand = "daab_AddAddress";
			DbCommand dbCommandWrapper = db.GetStoredProcCommand(sqlCommand);

			// Add parameters
			db.AddOutParameter(dbCommandWrapper, "@AddressID", DbType.Int32, 4);
			db.AddInParameter(dbCommandWrapper, "@CountryID", DbType.Int32, SetNullValue((_CountryID == 0), _CountryID));
			db.AddInParameter(dbCommandWrapper, "@CityID", DbType.Int32, SetNullValue((_CityID == 0), _CityID));
			db.AddInParameter(dbCommandWrapper, "@DistrictID", DbType.Int32, SetNullValue((_DistrictID == 0), _DistrictID));
			db.AddInParameter(dbCommandWrapper, "@Area", DbType.String, SetNullValue((_Area == string.Empty), _Area));
			db.AddInParameter(dbCommandWrapper, "@Street", DbType.String, SetNullValue((_Street == string.Empty), _Street));
			db.AddInParameter(dbCommandWrapper, "@Building", DbType.String, SetNullValue((_Building == string.Empty), _Building));
			db.AddInParameter(dbCommandWrapper, "@AccountID", DbType.Int32, SetNullValue((_AccountID == 0), _AccountID));
			db.AddInParameter(dbCommandWrapper, "@AddressTypeID", DbType.Int32, SetNullValue((_AddressTypeID == 0), _AddressTypeID));
			db.AddInParameter(dbCommandWrapper, "@Del", DbType.Boolean, SetNullValue((_Del == false), _Del));

			db.ExecuteNonQuery(dbCommandWrapper);
			
			// Save output parameter values
			object param;
			param = db.GetParameterValue(dbCommandWrapper, "@AddressID");
			if (param == DBNull.Value) return false;
			_AddressID = (int)param;
			
			return true;
		}

		/// <summary>
		/// Updates the current instance data in the database.
		/// </summary>
		/// <returns>Returns True if saved successfully, False otherwise.</returns>
		public bool Update()
		{
			// Create the Database object, using the default database service. The
			// default database service is determined through configuration.
			Database db = DatabaseFactory.CreateDatabase();

			string sqlCommand = "daab_UpdateAddress";
			DbCommand dbCommandWrapper = db.GetStoredProcCommand(sqlCommand);

			// Add parameters
			db.AddInParameter(dbCommandWrapper, "@AddressID", DbType.Int32, _AddressID);
			db.AddInParameter(dbCommandWrapper, "@CountryID", DbType.Int32, SetNullValue((_CountryID == 0), _CountryID));
			db.AddInParameter(dbCommandWrapper, "@CityID", DbType.Int32, SetNullValue((_CityID == 0), _CityID));
			db.AddInParameter(dbCommandWrapper, "@DistrictID", DbType.Int32, SetNullValue((_DistrictID == 0), _DistrictID));
			db.AddInParameter(dbCommandWrapper, "@Area", DbType.String, SetNullValue((_Area == string.Empty), _Area));
			db.AddInParameter(dbCommandWrapper, "@Street", DbType.String, SetNullValue((_Street == string.Empty), _Street));
			db.AddInParameter(dbCommandWrapper, "@Building", DbType.String, SetNullValue((_Building == string.Empty), _Building));
			db.AddInParameter(dbCommandWrapper, "@AccountID", DbType.Int32, SetNullValue((_AccountID == 0), _AccountID));
			db.AddInParameter(dbCommandWrapper, "@AddressTypeID", DbType.Int32, SetNullValue((_AddressTypeID == 0), _AddressTypeID));
			db.AddInParameter(dbCommandWrapper, "@Del", DbType.Boolean, SetNullValue((_Del == false), _Del));

			try
			{
				db.ExecuteNonQuery(dbCommandWrapper);
				
				// Save output parameter values
				object param;
				param = db.GetParameterValue(dbCommandWrapper, "@AddressID");
				if (param == DBNull.Value) return false;
				_AddressID = (int)param;
				
				return true;
			}
			catch
			{
				return false;
			}
		}

		/// <summary>
		/// Removes info from the database, based on the requested primary key.
		/// </summary>
		/// <param name="AddressID"></param>
		public static void Remove(int AddressID)
		{
			// Create the Database object, using the default database service. The
			// default database service is determined through configuration.
			Database db = DatabaseFactory.CreateDatabase();

			string sqlCommand = "daab_DeleteAddress";
			DbCommand dbCommandWrapper = db.GetStoredProcCommand(sqlCommand);

			// Add primary keys to command wrapper.
			db.AddInParameter(dbCommandWrapper, "@AddressID", DbType.Int32, AddressID);

			db.ExecuteNonQuery(dbCommandWrapper);
		}
		
		/// <summary>
		/// Serializes the current instance data to an Xml string.
		/// </summary>
		/// <returns>A string containing the Xml representation of the object.</returns>
		virtual public string ToXml()
		{
			// DataSet that will hold the returned results		
			DataSet ds = this.LoadByPrimaryKey(_AddressID);
			StringWriter writer = new StringWriter(); 
			ds.WriteXml(writer); 
			return writer.ToString(); 
		}

		/// <summary>
		/// Utility function that returns a DBNull.Value if requested. The comparison is done inline
		/// in the Insert() and Update() functions.
		/// </summary>
		private object SetNullValue(bool isNullValue, object value)
		{
			if (isNullValue)
				return DBNull.Value;
			else
				return value;
		}
	}
}
