
// Generated by MyGeneration Version # (1.3.0.3)

using System;
using System.Data.Common;
using System.Data;
using Microsoft.Practices.EnterpriseLibrary.Data;

namespace EquitableGourmet
{
	public class AddressType : AddressTypeBase
	{
		#region < CONSTRUCTORES >
		
		public AddressType() : base()	{}
		
		#endregion
		
		
		
		// TODO: Agregue Código Adicional Aqui.
	}
}
