/*
'===============================================================================
'  Generated From - CSharp_DAAB_BusinessEntity.vbgen
' 
'  ** IMPORTANT  ** 
'  How to Generate your stored procedures:
' 
'  SQL      = SQL_DAAB_Net2_StoredProcs.vbgen
'  
'  This object is 'abstract' which means you need to inherit from it to be able
'  to instantiate it.  This is very easily done. You can override properties and
'  methods in your derived class, this allows you to regenerate this class at any
'  time and not worry about overwriting custom code. 
'
'  NEVER EDIT THIS FILE.
'
'  public class YourObject :  YourObjectBase
'  {
'
'  }
'
'===============================================================================
*/

// Generated by MyGeneration Version # (1.3.0.3)

using System;
using System.Data;
using System.Configuration;
using System.Collections;
using System.Collections.Specialized;
using System.Xml;
using System.IO;

using Microsoft.Practices.EnterpriseLibrary.Data;
using System.Data.Common;

namespace EquitableGourmet
{
	public abstract class AspNetUserClaimsBase
	{
		#region < VARIABLES >
		private int _Id;
		private string _UserId;
		private string _ClaimType;
		private string _ClaimValue;
		private bool _isNew;
		#endregion
		
		#region < CONSTRUCTORES >
		protected AspNetUserClaimsBase()
		{
			_Id = 0;
			_ClaimType = string.Empty;
			_ClaimValue = string.Empty;
		}
		
		protected AspNetUserClaimsBase(int Id) : this()
		{
			_Id = Id;
		}
	
		protected AspNetUserClaimsBase(int Id, string UserId, string ClaimType, string ClaimValue) : this()
		{
			_Id = Id;
			_UserId = UserId;
			_ClaimType = ClaimType;
			_ClaimValue = ClaimValue;
		}

		#endregion
		
		#region < Metodos para Obtención de Detalles >

		public static DataTable GetByAspNetUsers(string UserId)
		{
			Database db = DatabaseFactory.CreateDatabase();
            string sqlCommand = "Select * From AspNetUserClaims Where UserId = @UserId";
            DbCommand dbCommandWrapper = db.GetSqlStringCommand(sqlCommand);
			db.AddInParameter(dbCommandWrapper, "@UserId", DbType.String, UserId);

			DataTable t = db.ExecuteDataSet(dbCommandWrapper).Tables[0];
			
			t.Columns["UserId"].DefaultValue = UserId;

            return t;
		}

		#endregion
		
		#region < PROPIEDADES >
		
		public int Id
		{
			get	{ return _Id; }
			set	{ _Id = value; }
		}
		
		public string UserId
		{
			get	{ return _UserId; }
			set	{ _UserId = value; }
		}
		
		public string ClaimType
		{
			get	{ return _ClaimType; }
			set	{ _ClaimType = value; }
		}
		
		public string ClaimValue
		{
			get	{ return _ClaimValue; }
			set	{ _ClaimValue = value; }
		}
		
		public bool IsNew
		{
			get 
			{ 
				_isNew = (_Id == 0);
				return _isNew; 
			}
			set { _isNew = value; }
		}
		#endregion		

		#region Utilerias
		public static bool Existe(int Id)
		{
			Database db = DatabaseFactory.CreateDatabase();
			string sqlCommand = "daab_ExistsAspNetUserClaims";
			DbCommand dbCommandWrapper = db.GetStoredProcCommand(sqlCommand);

			// Add in parameters
			db.AddInParameter(dbCommandWrapper, "@Id", DbType.Int32, Id);

			// DataSet that will hold the returned results		
			// Note: connection closed by ExecuteDataSet method call 
			bool ret = false;
			int num = Convert.ToInt32(db.ExecuteScalar(dbCommandWrapper));
			ret = num > 0;
			return ret;
		}
		
		public static DataTable GetAllAspNetUserClaims()
		{
			Database db = DatabaseFactory.CreateDatabase();

			string sqlCommand = "daab_GetAllAspNetUserClaims";
			DbCommand dbCommandWrapper = db.GetStoredProcCommand(sqlCommand);
			DataTable ret = db.ExecuteDataSet(dbCommandWrapper).Tables[0];
			
            ret.PrimaryKey = new DataColumn[] { ret.Columns["Id"] };
			
            return ret;
		}
		
		public static void SaveAll(DataTable tabla)
		{
			Database db = DatabaseFactory.CreateDatabase();
			DbDataAdapter da = db.GetDataAdapter();
			
			da.SelectCommand = db.GetStoredProcCommand("daab_GetAllAspNetUserClaims");
            da.InsertCommand = db.GetStoredProcCommand("daab_AddAspNetUserClaims");
            da.UpdateCommand = db.GetStoredProcCommand("daab_UpdateAspNetUserClaims");
            da.DeleteCommand = db.GetStoredProcCommand("daab_DeleteAspNetUserClaims");
			
			#region Parametros de InsertCommand
			db.AddOutParameter(da.InsertCommand, "@Id", DbType.Int32, 4);
			db.AddInParameter(da.InsertCommand, "@UserId", DbType.String, "UserId", DataRowVersion.Default);
			db.AddInParameter(da.InsertCommand, "@ClaimType", DbType.String, "ClaimType", DataRowVersion.Default);
			db.AddInParameter(da.InsertCommand, "@ClaimValue", DbType.String, "ClaimValue", DataRowVersion.Default);

			#endregion
			
			#region Parametros de UpdateCommand
			db.AddInParameter(da.UpdateCommand, "@Id", DbType.Int32, "Id", DataRowVersion.Default);
			db.AddInParameter(da.UpdateCommand, "@UserId", DbType.String, "UserId", DataRowVersion.Default);
			db.AddInParameter(da.UpdateCommand, "@ClaimType", DbType.String, "ClaimType", DataRowVersion.Default);
			db.AddInParameter(da.UpdateCommand, "@ClaimValue", DbType.String, "ClaimValue", DataRowVersion.Default);

			#endregion
			
			#region Parametros de DeleteCommand
			db.AddInParameter(da.DeleteCommand, "@Id", DbType.Int32, "Id", DataRowVersion.Default);

			#endregion

			db.UpdateDataSet(tabla.DataSet, tabla.TableName, da.InsertCommand, da.UpdateCommand, da.DeleteCommand, UpdateBehavior.Standard);
		}
		#endregion

		/// <summary>
		/// Populates a dataset with info from the database, based on the requested primary key.
		/// </summary>
		/// <param name="Id"></param>
		/// <returns>A DataSet containing the results of the query</returns>
		private DataSet LoadByPrimaryKey(int Id)
		{
			// Create the Database object, using the default database service. The
			// default database service is determined through configuration.
			Database db = DatabaseFactory.CreateDatabase();

			string sqlCommand = "daab_GetAspNetUserClaims";
			DbCommand dbCommandWrapper = db.GetStoredProcCommand(sqlCommand);

			// Add in parameters
			db.AddInParameter(dbCommandWrapper, "@Id", DbType.Int32, Id);

			// DataSet that will hold the returned results		
			// Note: connection closed by ExecuteDataSet method call 
			return db.ExecuteDataSet(dbCommandWrapper);
		}
	
		/// <summary>
		/// Populates current instance of the object with info from the database, based on the requested primary key.
		/// </summary>
		/// <param name="Id"></param>
		public virtual void Load(int Id)
		{
			// DataSet that will hold the returned results		
			DataSet ds = this.LoadByPrimaryKey(Id);
			
			// Load member variables from datarow
			DataRow row = ds.Tables[0].Rows[0];
			_Id = (int)row["Id"];
			_UserId = (string)row["UserId"];
			_ClaimType = row.IsNull("ClaimType") ? string.Empty : (string)row["ClaimType"];
			_ClaimValue = row.IsNull("ClaimValue") ? string.Empty : (string)row["ClaimValue"];
		}

		/// <summary>
		/// Adds or updates information in the database depending on the primary key stored in the object instance.
		/// </summary>
		/// <returns>Returns True if saved successfully, False otherwise.</returns>
		public bool Save()
		{
			if (this.IsNew)
				return Insert();
			else
				return Update();
		}

		/// <summary>
		/// Inserts the current instance data into the database.
		/// </summary>
		/// <returns>Returns True if saved successfully, False otherwise.</returns>
		private bool Insert()
		{
			// Create the Database object, using the default database service. The
			// default database service is determined through configuration.
			Database db = DatabaseFactory.CreateDatabase();

			string sqlCommand = "daab_AddAspNetUserClaims";
			DbCommand dbCommandWrapper = db.GetStoredProcCommand(sqlCommand);

			// Add parameters
			db.AddOutParameter(dbCommandWrapper, "@Id", DbType.Int32, 4);
			db.AddInParameter(dbCommandWrapper, "@UserId", DbType.String, _UserId);
			db.AddInParameter(dbCommandWrapper, "@ClaimType", DbType.String, SetNullValue((_ClaimType == string.Empty), _ClaimType));
			db.AddInParameter(dbCommandWrapper, "@ClaimValue", DbType.String, SetNullValue((_ClaimValue == string.Empty), _ClaimValue));

			db.ExecuteNonQuery(dbCommandWrapper);
			
			// Save output parameter values
			object param;
			param = db.GetParameterValue(dbCommandWrapper, "@Id");
			if (param == DBNull.Value) return false;
			_Id = (int)param;
			
			return true;
		}

		/// <summary>
		/// Updates the current instance data in the database.
		/// </summary>
		/// <returns>Returns True if saved successfully, False otherwise.</returns>
		public bool Update()
		{
			// Create the Database object, using the default database service. The
			// default database service is determined through configuration.
			Database db = DatabaseFactory.CreateDatabase();

			string sqlCommand = "daab_UpdateAspNetUserClaims";
			DbCommand dbCommandWrapper = db.GetStoredProcCommand(sqlCommand);

			// Add parameters
			db.AddInParameter(dbCommandWrapper, "@Id", DbType.Int32, _Id);
			db.AddInParameter(dbCommandWrapper, "@UserId", DbType.String, _UserId);
			db.AddInParameter(dbCommandWrapper, "@ClaimType", DbType.String, SetNullValue((_ClaimType == string.Empty), _ClaimType));
			db.AddInParameter(dbCommandWrapper, "@ClaimValue", DbType.String, SetNullValue((_ClaimValue == string.Empty), _ClaimValue));

			try
			{
				db.ExecuteNonQuery(dbCommandWrapper);
				
				// Save output parameter values
				object param;
				param = db.GetParameterValue(dbCommandWrapper, "@Id");
				if (param == DBNull.Value) return false;
				_Id = (int)param;
				
				return true;
			}
			catch
			{
				return false;
			}
		}

		/// <summary>
		/// Removes info from the database, based on the requested primary key.
		/// </summary>
		/// <param name="Id"></param>
		public static void Remove(int Id)
		{
			// Create the Database object, using the default database service. The
			// default database service is determined through configuration.
			Database db = DatabaseFactory.CreateDatabase();

			string sqlCommand = "daab_DeleteAspNetUserClaims";
			DbCommand dbCommandWrapper = db.GetStoredProcCommand(sqlCommand);

			// Add primary keys to command wrapper.
			db.AddInParameter(dbCommandWrapper, "@Id", DbType.Int32, Id);

			db.ExecuteNonQuery(dbCommandWrapper);
		}
		
		/// <summary>
		/// Serializes the current instance data to an Xml string.
		/// </summary>
		/// <returns>A string containing the Xml representation of the object.</returns>
		virtual public string ToXml()
		{
			// DataSet that will hold the returned results		
			DataSet ds = this.LoadByPrimaryKey(_Id);
			StringWriter writer = new StringWriter(); 
			ds.WriteXml(writer); 
			return writer.ToString(); 
		}

		/// <summary>
		/// Utility function that returns a DBNull.Value if requested. The comparison is done inline
		/// in the Insert() and Update() functions.
		/// </summary>
		private object SetNullValue(bool isNullValue, object value)
		{
			if (isNullValue)
				return DBNull.Value;
			else
				return value;
		}
	}
}
