/*
'===============================================================================
'  Generated From - CSharp_DAAB_BusinessEntity.vbgen
' 
'  ** IMPORTANT  ** 
'  How to Generate your stored procedures:
' 
'  SQL      = SQL_DAAB_Net2_StoredProcs.vbgen
'  
'  This object is 'abstract' which means you need to inherit from it to be able
'  to instantiate it.  This is very easily done. You can override properties and
'  methods in your derived class, this allows you to regenerate this class at any
'  time and not worry about overwriting custom code. 
'
'  NEVER EDIT THIS FILE.
'
'  public class YourObject :  YourObjectBase
'  {
'
'  }
'
'===============================================================================
*/

// Generated by MyGeneration Version # (1.3.0.3)

using System;
using System.Data;
using System.Configuration;
using System.Collections;
using System.Collections.Specialized;
using System.Xml;
using System.IO;

using Microsoft.Practices.EnterpriseLibrary.Data;
using System.Data.Common;

namespace EquitableGourmet
{
	public abstract class MenuBase
	{
		#region < VARIABLES >
		private int _MenuID;
		private int _ParentMenuID;
		private int _UserPermissionsID;
		private string _Name;
		private int _DisplayOrder;
		private string _Class;
		private bool _Del;
		private bool _isNew;
		#endregion
		
		#region < CONSTRUCTORES >
		protected MenuBase()
		{
			_MenuID = 0;
			_ParentMenuID = 0;
			_UserPermissionsID = 0;
			_Name = string.Empty;
			_DisplayOrder = 0;
			_Class = string.Empty;
			_Del = false;
		}
		
		protected MenuBase(int MenuID) : this()
		{
			_MenuID = MenuID;
		}
	
		protected MenuBase(int MenuID, int ParentMenuID, int UserPermissionsID, string Name, int DisplayOrder, string Class, bool Del) : this()
		{
			_MenuID = MenuID;
			_ParentMenuID = ParentMenuID;
			_UserPermissionsID = UserPermissionsID;
			_Name = Name;
			_DisplayOrder = DisplayOrder;
			_Class = Class;
			_Del = Del;
		}

		#endregion
		
		#region < Metodos para Obtención de Detalles >

		public static DataTable GetByMenu(int ParentMenuID)
		{
			Database db = DatabaseFactory.CreateDatabase();
            string sqlCommand = "Select * From Menu Where ParentMenuID = @ParentMenuID";
            DbCommand dbCommandWrapper = db.GetSqlStringCommand(sqlCommand);
			db.AddInParameter(dbCommandWrapper, "@ParentMenuID", DbType.Int32, ParentMenuID);

			DataTable t = db.ExecuteDataSet(dbCommandWrapper).Tables[0];
			
			t.Columns["ParentMenuID"].DefaultValue = ParentMenuID;

            return t;
		}

		public static DataTable GetByUserPermissions(int UserPermissionsID)
		{
			Database db = DatabaseFactory.CreateDatabase();
            string sqlCommand = "Select * From Menu Where UserPermissionsID = @UserPermissionsID";
            DbCommand dbCommandWrapper = db.GetSqlStringCommand(sqlCommand);
			db.AddInParameter(dbCommandWrapper, "@UserPermissionsID", DbType.Int32, UserPermissionsID);

			DataTable t = db.ExecuteDataSet(dbCommandWrapper).Tables[0];
			
			t.Columns["UserPermissionsID"].DefaultValue = UserPermissionsID;

            return t;
		}

		#endregion
		
		#region < PROPIEDADES >
		
		public int MenuID
		{
			get	{ return _MenuID; }
			set	{ _MenuID = value; }
		}
		
		public int ParentMenuID
		{
			get	{ return _ParentMenuID; }
			set	{ _ParentMenuID = value; }
		}
		
		public int UserPermissionsID
		{
			get	{ return _UserPermissionsID; }
			set	{ _UserPermissionsID = value; }
		}
		
		public string Name
		{
			get	{ return _Name; }
			set	{ _Name = value; }
		}
		
		public int DisplayOrder
		{
			get	{ return _DisplayOrder; }
			set	{ _DisplayOrder = value; }
		}
		
		public string Class
		{
			get	{ return _Class; }
			set	{ _Class = value; }
		}
		
		public bool Del
		{
			get	{ return _Del; }
			set	{ _Del = value; }
		}
		
		public bool IsNew
		{
			get 
			{ 
				_isNew = (_MenuID == 0);
				return _isNew; 
			}
			set { _isNew = value; }
		}
		#endregion		

		#region Utilerias
		public static bool Existe(int MenuID)
		{
			Database db = DatabaseFactory.CreateDatabase();
			string sqlCommand = "daab_ExistsMenu";
			DbCommand dbCommandWrapper = db.GetStoredProcCommand(sqlCommand);

			// Add in parameters
			db.AddInParameter(dbCommandWrapper, "@MenuID", DbType.Int32, MenuID);

			// DataSet that will hold the returned results		
			// Note: connection closed by ExecuteDataSet method call 
			bool ret = false;
			int num = Convert.ToInt32(db.ExecuteScalar(dbCommandWrapper));
			ret = num > 0;
			return ret;
		}
		
		public static DataTable GetAllMenu()
		{
			Database db = DatabaseFactory.CreateDatabase();

			string sqlCommand = "daab_GetAllMenu";
			DbCommand dbCommandWrapper = db.GetStoredProcCommand(sqlCommand);
			DataTable ret = db.ExecuteDataSet(dbCommandWrapper).Tables[0];
			
            ret.PrimaryKey = new DataColumn[] { ret.Columns["MenuID"] };
			
            return ret;
		}
		
		public static void SaveAll(DataTable tabla)
		{
			Database db = DatabaseFactory.CreateDatabase();
			DbDataAdapter da = db.GetDataAdapter();
			
			da.SelectCommand = db.GetStoredProcCommand("daab_GetAllMenu");
            da.InsertCommand = db.GetStoredProcCommand("daab_AddMenu");
            da.UpdateCommand = db.GetStoredProcCommand("daab_UpdateMenu");
            da.DeleteCommand = db.GetStoredProcCommand("daab_DeleteMenu");
			
			#region Parametros de InsertCommand
			db.AddOutParameter(da.InsertCommand, "@MenuID", DbType.Int32, 4);
			db.AddInParameter(da.InsertCommand, "@ParentMenuID", DbType.Int32, "ParentMenuID", DataRowVersion.Default);
			db.AddInParameter(da.InsertCommand, "@UserPermissionsID", DbType.Int32, "UserPermissionsID", DataRowVersion.Default);
			db.AddInParameter(da.InsertCommand, "@Name", DbType.String, "Name", DataRowVersion.Default);
			db.AddInParameter(da.InsertCommand, "@DisplayOrder", DbType.Int32, "DisplayOrder", DataRowVersion.Default);
			db.AddInParameter(da.InsertCommand, "@Class", DbType.String, "Class", DataRowVersion.Default);
			db.AddInParameter(da.InsertCommand, "@Del", DbType.Boolean, "Del", DataRowVersion.Default);

			#endregion
			
			#region Parametros de UpdateCommand
			db.AddInParameter(da.UpdateCommand, "@MenuID", DbType.Int32, "MenuID", DataRowVersion.Default);
			db.AddInParameter(da.UpdateCommand, "@ParentMenuID", DbType.Int32, "ParentMenuID", DataRowVersion.Default);
			db.AddInParameter(da.UpdateCommand, "@UserPermissionsID", DbType.Int32, "UserPermissionsID", DataRowVersion.Default);
			db.AddInParameter(da.UpdateCommand, "@Name", DbType.String, "Name", DataRowVersion.Default);
			db.AddInParameter(da.UpdateCommand, "@DisplayOrder", DbType.Int32, "DisplayOrder", DataRowVersion.Default);
			db.AddInParameter(da.UpdateCommand, "@Class", DbType.String, "Class", DataRowVersion.Default);
			db.AddInParameter(da.UpdateCommand, "@Del", DbType.Boolean, "Del", DataRowVersion.Default);

			#endregion
			
			#region Parametros de DeleteCommand
			db.AddInParameter(da.DeleteCommand, "@MenuID", DbType.Int32, "MenuID", DataRowVersion.Default);

			#endregion

			db.UpdateDataSet(tabla.DataSet, tabla.TableName, da.InsertCommand, da.UpdateCommand, da.DeleteCommand, UpdateBehavior.Standard);
		}
		#endregion

		/// <summary>
		/// Populates a dataset with info from the database, based on the requested primary key.
		/// </summary>
		/// <param name="MenuID"></param>
		/// <returns>A DataSet containing the results of the query</returns>
		private DataSet LoadByPrimaryKey(int MenuID)
		{
			// Create the Database object, using the default database service. The
			// default database service is determined through configuration.
			Database db = DatabaseFactory.CreateDatabase();

			string sqlCommand = "daab_GetMenu";
			DbCommand dbCommandWrapper = db.GetStoredProcCommand(sqlCommand);

			// Add in parameters
			db.AddInParameter(dbCommandWrapper, "@MenuID", DbType.Int32, MenuID);

			// DataSet that will hold the returned results		
			// Note: connection closed by ExecuteDataSet method call 
			return db.ExecuteDataSet(dbCommandWrapper);
		}
	
		/// <summary>
		/// Populates current instance of the object with info from the database, based on the requested primary key.
		/// </summary>
		/// <param name="MenuID"></param>
		public virtual void Load(int MenuID)
		{
			// DataSet that will hold the returned results		
			DataSet ds = this.LoadByPrimaryKey(MenuID);
			
			// Load member variables from datarow
			DataRow row = ds.Tables[0].Rows[0];
			_MenuID = (int)row["MenuID"];
			_ParentMenuID = row.IsNull("ParentMenuID") ? 0 : (int)row["ParentMenuID"];
			_UserPermissionsID = row.IsNull("UserPermissionsID") ? 0 : (int)row["UserPermissionsID"];
			_Name = row.IsNull("Name") ? string.Empty : (string)row["Name"];
			_DisplayOrder = row.IsNull("DisplayOrder") ? 0 : (int)row["DisplayOrder"];
			_Class = row.IsNull("Class") ? string.Empty : (string)row["Class"];
			_Del = row.IsNull("Del") ? false : (bool)row["Del"];
		}

		/// <summary>
		/// Adds or updates information in the database depending on the primary key stored in the object instance.
		/// </summary>
		/// <returns>Returns True if saved successfully, False otherwise.</returns>
		public bool Save()
		{
			if (this.IsNew)
				return Insert();
			else
				return Update();
		}

		/// <summary>
		/// Inserts the current instance data into the database.
		/// </summary>
		/// <returns>Returns True if saved successfully, False otherwise.</returns>
		private bool Insert()
		{
			// Create the Database object, using the default database service. The
			// default database service is determined through configuration.
			Database db = DatabaseFactory.CreateDatabase();

			string sqlCommand = "daab_AddMenu";
			DbCommand dbCommandWrapper = db.GetStoredProcCommand(sqlCommand);

			// Add parameters
			db.AddOutParameter(dbCommandWrapper, "@MenuID", DbType.Int32, 4);
			db.AddInParameter(dbCommandWrapper, "@ParentMenuID", DbType.Int32, SetNullValue((_ParentMenuID == 0), _ParentMenuID));
			db.AddInParameter(dbCommandWrapper, "@UserPermissionsID", DbType.Int32, SetNullValue((_UserPermissionsID == 0), _UserPermissionsID));
			db.AddInParameter(dbCommandWrapper, "@Name", DbType.String, SetNullValue((_Name == string.Empty), _Name));
			db.AddInParameter(dbCommandWrapper, "@DisplayOrder", DbType.Int32, SetNullValue((_DisplayOrder == 0), _DisplayOrder));
			db.AddInParameter(dbCommandWrapper, "@Class", DbType.String, SetNullValue((_Class == string.Empty), _Class));
            db.AddInParameter(dbCommandWrapper, "@Del", DbType.Boolean, SetNullValue((_Del == true), _Del));

			db.ExecuteNonQuery(dbCommandWrapper);
			
			// Save output parameter values
			object param;
			param = db.GetParameterValue(dbCommandWrapper, "@MenuID");
			if (param == DBNull.Value) return false;
			_MenuID = (int)param;
			
			return true;
		}

		/// <summary>
		/// Updates the current instance data in the database.
		/// </summary>
		/// <returns>Returns True if saved successfully, False otherwise.</returns>
		public bool Update()
		{
			// Create the Database object, using the default database service. The
			// default database service is determined through configuration.
			Database db = DatabaseFactory.CreateDatabase();

			string sqlCommand = "daab_UpdateMenu";
			DbCommand dbCommandWrapper = db.GetStoredProcCommand(sqlCommand);

			// Add parameters
			db.AddInParameter(dbCommandWrapper, "@MenuID", DbType.Int32, _MenuID);
			db.AddInParameter(dbCommandWrapper, "@ParentMenuID", DbType.Int32, SetNullValue((_ParentMenuID == 0), _ParentMenuID));
			db.AddInParameter(dbCommandWrapper, "@UserPermissionsID", DbType.Int32, SetNullValue((_UserPermissionsID == 0), _UserPermissionsID));
			db.AddInParameter(dbCommandWrapper, "@Name", DbType.String, SetNullValue((_Name == string.Empty), _Name));
			db.AddInParameter(dbCommandWrapper, "@DisplayOrder", DbType.Int32, SetNullValue((_DisplayOrder == 0), _DisplayOrder));
			db.AddInParameter(dbCommandWrapper, "@Class", DbType.String, SetNullValue((_Class == string.Empty), _Class));
			db.AddInParameter(dbCommandWrapper, "@Del", DbType.Boolean, SetNullValue((_Del == false), _Del));

			try
			{
				db.ExecuteNonQuery(dbCommandWrapper);
				
				// Save output parameter values
				object param;
				param = db.GetParameterValue(dbCommandWrapper, "@MenuID");
				if (param == DBNull.Value) return false;
				_MenuID = (int)param;
				
				return true;
			}
			catch
			{
				return false;
			}
		}

		/// <summary>
		/// Removes info from the database, based on the requested primary key.
		/// </summary>
		/// <param name="MenuID"></param>
		public static void Remove(int MenuID)
		{
			// Create the Database object, using the default database service. The
			// default database service is determined through configuration.
			Database db = DatabaseFactory.CreateDatabase();

			string sqlCommand = "daab_DeleteMenu";
			DbCommand dbCommandWrapper = db.GetStoredProcCommand(sqlCommand);

			// Add primary keys to command wrapper.
			db.AddInParameter(dbCommandWrapper, "@MenuID", DbType.Int32, MenuID);

			db.ExecuteNonQuery(dbCommandWrapper);
		}
		
		/// <summary>
		/// Serializes the current instance data to an Xml string.
		/// </summary>
		/// <returns>A string containing the Xml representation of the object.</returns>
		virtual public string ToXml()
		{
			// DataSet that will hold the returned results		
			DataSet ds = this.LoadByPrimaryKey(_MenuID);
			StringWriter writer = new StringWriter(); 
			ds.WriteXml(writer); 
			return writer.ToString(); 
		}

		/// <summary>
		/// Utility function that returns a DBNull.Value if requested. The comparison is done inline
		/// in the Insert() and Update() functions.
		/// </summary>
		private object SetNullValue(bool isNullValue, object value)
		{
			if (isNullValue)
				return DBNull.Value;
			else
				return value;
		}
	}
}
