/*
'===============================================================================
'  Generated From - CSharp_DAAB_BusinessEntity.vbgen
' 
'  ** IMPORTANT  ** 
'  How to Generate your stored procedures:
' 
'  SQL      = SQL_DAAB_Net2_StoredProcs.vbgen
'  
'  This object is 'abstract' which means you need to inherit from it to be able
'  to instantiate it.  This is very easily done. You can override properties and
'  methods in your derived class, this allows you to regenerate this class at any
'  time and not worry about overwriting custom code. 
'
'  NEVER EDIT THIS FILE.
'
'  public class YourObject :  YourObjectBase
'  {
'
'  }
'
'===============================================================================
*/

// Generated by MyGeneration Version # (1.3.0.3)

using System;
using System.Data;
using System.Configuration;
using System.Collections;
using System.Collections.Specialized;
using System.Xml;
using System.IO;

using Microsoft.Practices.EnterpriseLibrary.Data;
using System.Data.Common;

namespace EquitableGourmet
{
	public abstract class OrderNoteBase
	{
		#region < VARIABLES >
		private int _OrderNoteID;
		private int _OrderID;
		private int _UserID;
		private string _Title;
		private string _Number;
		private string _Note;
		private bool _Del;
		private bool _isNew;
		#endregion
		
		#region < CONSTRUCTORES >
		protected OrderNoteBase()
		{
			_OrderNoteID = 0;
			_OrderID = 0;
			_UserID = 0;
			_Title = string.Empty;
			_Number = string.Empty;
			_Note = string.Empty;
			_Del = false;
		}
		
		protected OrderNoteBase(int OrderNoteID) : this()
		{
			_OrderNoteID = OrderNoteID;
		}
	
		protected OrderNoteBase(int OrderNoteID, int OrderID, int UserID, string Title, string Number, string Note, bool Del) : this()
		{
			_OrderNoteID = OrderNoteID;
			_OrderID = OrderID;
			_UserID = UserID;
			_Title = Title;
			_Number = Number;
			_Note = Note;
			_Del = Del;
		}

		#endregion
		
		#region < Metodos para Obtención de Detalles >

		public static DataTable GetByOrder(int OrderID)
		{
			Database db = DatabaseFactory.CreateDatabase();
            string sqlCommand = "Select * From OrderNote Where OrderID = @OrderID";
            DbCommand dbCommandWrapper = db.GetSqlStringCommand(sqlCommand);
			db.AddInParameter(dbCommandWrapper, "@OrderID", DbType.Int32, OrderID);

			DataTable t = db.ExecuteDataSet(dbCommandWrapper).Tables[0];
			
			t.Columns["OrderID"].DefaultValue = OrderID;

            return t;
		}

		#endregion
		
		#region < PROPIEDADES >
		
		public int OrderNoteID
		{
			get	{ return _OrderNoteID; }
			set	{ _OrderNoteID = value; }
		}
		
		public int OrderID
		{
			get	{ return _OrderID; }
			set	{ _OrderID = value; }
		}
		
		public int UserID
		{
			get	{ return _UserID; }
			set	{ _UserID = value; }
		}
		
		public string Title
		{
			get	{ return _Title; }
			set	{ _Title = value; }
		}
		
		public string Number
		{
			get	{ return _Number; }
			set	{ _Number = value; }
		}
		
		public string Note
		{
			get	{ return _Note; }
			set	{ _Note = value; }
		}
		
		public bool Del
		{
			get	{ return _Del; }
			set	{ _Del = value; }
		}
		
		public bool IsNew
		{
			get 
			{ 
				_isNew = (_OrderNoteID == 0);
				return _isNew; 
			}
			set { _isNew = value; }
		}
		#endregion		

		#region Utilerias
		public static bool Existe(int OrderNoteID)
		{
			Database db = DatabaseFactory.CreateDatabase();
			string sqlCommand = "daab_ExistsOrderNote";
			DbCommand dbCommandWrapper = db.GetStoredProcCommand(sqlCommand);

			// Add in parameters
			db.AddInParameter(dbCommandWrapper, "@OrderNoteID", DbType.Int32, OrderNoteID);

			// DataSet that will hold the returned results		
			// Note: connection closed by ExecuteDataSet method call 
			bool ret = false;
			int num = Convert.ToInt32(db.ExecuteScalar(dbCommandWrapper));
			ret = num > 0;
			return ret;
		}
		
		public static DataTable GetAllOrderNote()
		{
			Database db = DatabaseFactory.CreateDatabase();

			string sqlCommand = "daab_GetAllOrderNote";
			DbCommand dbCommandWrapper = db.GetStoredProcCommand(sqlCommand);
			DataTable ret = db.ExecuteDataSet(dbCommandWrapper).Tables[0];
			
            ret.PrimaryKey = new DataColumn[] { ret.Columns["OrderNoteID"] };
			
            return ret;
		}
		
		public static void SaveAll(DataTable tabla)
		{
			Database db = DatabaseFactory.CreateDatabase();
			DbDataAdapter da = db.GetDataAdapter();
			
			da.SelectCommand = db.GetStoredProcCommand("daab_GetAllOrderNote");
            da.InsertCommand = db.GetStoredProcCommand("daab_AddOrderNote");
            da.UpdateCommand = db.GetStoredProcCommand("daab_UpdateOrderNote");
            da.DeleteCommand = db.GetStoredProcCommand("daab_DeleteOrderNote");
			
			#region Parametros de InsertCommand
			db.AddOutParameter(da.InsertCommand, "@OrderNoteID", DbType.Int32, 4);
			db.AddInParameter(da.InsertCommand, "@OrderID", DbType.Int32, "OrderID", DataRowVersion.Default);
			db.AddInParameter(da.InsertCommand, "@UserID", DbType.Int32, "UserID", DataRowVersion.Default);
			db.AddInParameter(da.InsertCommand, "@Title", DbType.String, "Title", DataRowVersion.Default);
			db.AddInParameter(da.InsertCommand, "@Number", DbType.String, "Number", DataRowVersion.Default);
			db.AddInParameter(da.InsertCommand, "@Note", DbType.String, "Note", DataRowVersion.Default);
			db.AddInParameter(da.InsertCommand, "@Del", DbType.Boolean, "Del", DataRowVersion.Default);

			#endregion
			
			#region Parametros de UpdateCommand
			db.AddInParameter(da.UpdateCommand, "@OrderNoteID", DbType.Int32, "OrderNoteID", DataRowVersion.Default);
			db.AddInParameter(da.UpdateCommand, "@OrderID", DbType.Int32, "OrderID", DataRowVersion.Default);
			db.AddInParameter(da.UpdateCommand, "@UserID", DbType.Int32, "UserID", DataRowVersion.Default);
			db.AddInParameter(da.UpdateCommand, "@Title", DbType.String, "Title", DataRowVersion.Default);
			db.AddInParameter(da.UpdateCommand, "@Number", DbType.String, "Number", DataRowVersion.Default);
			db.AddInParameter(da.UpdateCommand, "@Note", DbType.String, "Note", DataRowVersion.Default);
			db.AddInParameter(da.UpdateCommand, "@Del", DbType.Boolean, "Del", DataRowVersion.Default);

			#endregion
			
			#region Parametros de DeleteCommand
			db.AddInParameter(da.DeleteCommand, "@OrderNoteID", DbType.Int32, "OrderNoteID", DataRowVersion.Default);

			#endregion

			db.UpdateDataSet(tabla.DataSet, tabla.TableName, da.InsertCommand, da.UpdateCommand, da.DeleteCommand, UpdateBehavior.Standard);
		}
		#endregion

		/// <summary>
		/// Populates a dataset with info from the database, based on the requested primary key.
		/// </summary>
		/// <param name="OrderNoteID"></param>
		/// <returns>A DataSet containing the results of the query</returns>
		private DataSet LoadByPrimaryKey(int OrderNoteID)
		{
			// Create the Database object, using the default database service. The
			// default database service is determined through configuration.
			Database db = DatabaseFactory.CreateDatabase();

			string sqlCommand = "daab_GetOrderNote";
			DbCommand dbCommandWrapper = db.GetStoredProcCommand(sqlCommand);

			// Add in parameters
			db.AddInParameter(dbCommandWrapper, "@OrderNoteID", DbType.Int32, OrderNoteID);

			// DataSet that will hold the returned results		
			// Note: connection closed by ExecuteDataSet method call 
			return db.ExecuteDataSet(dbCommandWrapper);
		}
	
		/// <summary>
		/// Populates current instance of the object with info from the database, based on the requested primary key.
		/// </summary>
		/// <param name="OrderNoteID"></param>
		public virtual void Load(int OrderNoteID)
		{
			// DataSet that will hold the returned results		
			DataSet ds = this.LoadByPrimaryKey(OrderNoteID);
			
			// Load member variables from datarow
			DataRow row = ds.Tables[0].Rows[0];
			_OrderNoteID = (int)row["OrderNoteID"];
			_OrderID = row.IsNull("OrderID") ? 0 : (int)row["OrderID"];
			_UserID = row.IsNull("UserID") ? 0 : (int)row["UserID"];
			_Title = row.IsNull("Title") ? string.Empty : (string)row["Title"];
			_Number = row.IsNull("Number") ? string.Empty : (string)row["Number"];
			_Note = row.IsNull("Note") ? string.Empty : (string)row["Note"];
			_Del = row.IsNull("Del") ? false : (bool)row["Del"];
		}

		/// <summary>
		/// Adds or updates information in the database depending on the primary key stored in the object instance.
		/// </summary>
		/// <returns>Returns True if saved successfully, False otherwise.</returns>
		public bool Save()
		{
			if (this.IsNew)
				return Insert();
			else
				return Update();
		}

		/// <summary>
		/// Inserts the current instance data into the database.
		/// </summary>
		/// <returns>Returns True if saved successfully, False otherwise.</returns>
		private bool Insert()
		{
			// Create the Database object, using the default database service. The
			// default database service is determined through configuration.
			Database db = DatabaseFactory.CreateDatabase();

			string sqlCommand = "daab_AddOrderNote";
			DbCommand dbCommandWrapper = db.GetStoredProcCommand(sqlCommand);

			// Add parameters
			db.AddOutParameter(dbCommandWrapper, "@OrderNoteID", DbType.Int32, 4);
			db.AddInParameter(dbCommandWrapper, "@OrderID", DbType.Int32, SetNullValue((_OrderID == 0), _OrderID));
			db.AddInParameter(dbCommandWrapper, "@UserID", DbType.Int32, SetNullValue((_UserID == 0), _UserID));
			db.AddInParameter(dbCommandWrapper, "@Title", DbType.String, SetNullValue((_Title == string.Empty), _Title));
			db.AddInParameter(dbCommandWrapper, "@Number", DbType.String, SetNullValue((_Number == string.Empty), _Number));
			db.AddInParameter(dbCommandWrapper, "@Note", DbType.String, SetNullValue((_Note == string.Empty), _Note));
            db.AddInParameter(dbCommandWrapper, "@Del", DbType.Boolean, SetNullValue((_Del == true), _Del));

			db.ExecuteNonQuery(dbCommandWrapper);
			
			// Save output parameter values
			object param;
			param = db.GetParameterValue(dbCommandWrapper, "@OrderNoteID");
			if (param == DBNull.Value) return false;
			_OrderNoteID = (int)param;
			
			return true;
		}

		/// <summary>
		/// Updates the current instance data in the database.
		/// </summary>
		/// <returns>Returns True if saved successfully, False otherwise.</returns>
		public bool Update()
		{
			// Create the Database object, using the default database service. The
			// default database service is determined through configuration.
			Database db = DatabaseFactory.CreateDatabase();

			string sqlCommand = "daab_UpdateOrderNote";
			DbCommand dbCommandWrapper = db.GetStoredProcCommand(sqlCommand);

			// Add parameters
			db.AddInParameter(dbCommandWrapper, "@OrderNoteID", DbType.Int32, _OrderNoteID);
			db.AddInParameter(dbCommandWrapper, "@OrderID", DbType.Int32, SetNullValue((_OrderID == 0), _OrderID));
			db.AddInParameter(dbCommandWrapper, "@UserID", DbType.Int32, SetNullValue((_UserID == 0), _UserID));
			db.AddInParameter(dbCommandWrapper, "@Title", DbType.String, SetNullValue((_Title == string.Empty), _Title));
			db.AddInParameter(dbCommandWrapper, "@Number", DbType.String, SetNullValue((_Number == string.Empty), _Number));
			db.AddInParameter(dbCommandWrapper, "@Note", DbType.String, SetNullValue((_Note == string.Empty), _Note));
			db.AddInParameter(dbCommandWrapper, "@Del", DbType.Boolean, SetNullValue((_Del == false), _Del));

			try
			{
				db.ExecuteNonQuery(dbCommandWrapper);
				
				// Save output parameter values
				object param;
				param = db.GetParameterValue(dbCommandWrapper, "@OrderNoteID");
				if (param == DBNull.Value) return false;
				_OrderNoteID = (int)param;
				
				return true;
			}
			catch
			{
				return false;
			}
		}

		/// <summary>
		/// Removes info from the database, based on the requested primary key.
		/// </summary>
		/// <param name="OrderNoteID"></param>
		public static void Remove(int OrderNoteID)
		{
			// Create the Database object, using the default database service. The
			// default database service is determined through configuration.
			Database db = DatabaseFactory.CreateDatabase();

			string sqlCommand = "daab_DeleteOrderNote";
			DbCommand dbCommandWrapper = db.GetStoredProcCommand(sqlCommand);

			// Add primary keys to command wrapper.
			db.AddInParameter(dbCommandWrapper, "@OrderNoteID", DbType.Int32, OrderNoteID);

			db.ExecuteNonQuery(dbCommandWrapper);
		}
		
		/// <summary>
		/// Serializes the current instance data to an Xml string.
		/// </summary>
		/// <returns>A string containing the Xml representation of the object.</returns>
		virtual public string ToXml()
		{
			// DataSet that will hold the returned results		
			DataSet ds = this.LoadByPrimaryKey(_OrderNoteID);
			StringWriter writer = new StringWriter(); 
			ds.WriteXml(writer); 
			return writer.ToString(); 
		}

		/// <summary>
		/// Utility function that returns a DBNull.Value if requested. The comparison is done inline
		/// in the Insert() and Update() functions.
		/// </summary>
		private object SetNullValue(bool isNullValue, object value)
		{
			if (isNullValue)
				return DBNull.Value;
			else
				return value;
		}
	}
}
