/*
'===============================================================================
'  Generated From - CSharp_DAAB_BusinessEntity.vbgen
' 
'  ** IMPORTANT  ** 
'  How to Generate your stored procedures:
' 
'  SQL      = SQL_DAAB_Net2_StoredProcs.vbgen
'  
'  This object is 'abstract' which means you need to inherit from it to be able
'  to instantiate it.  This is very easily done. You can override properties and
'  methods in your derived class, this allows you to regenerate this class at any
'  time and not worry about overwriting custom code. 
'
'  NEVER EDIT THIS FILE.
'
'  public class YourObject :  YourObjectBase
'  {
'
'  }
'
'===============================================================================
*/

// Generated by MyGeneration Version # (1.3.0.3)

using System;
using System.Data;
using System.Configuration;
using System.Collections;
using System.Collections.Specialized;
using System.Xml;
using System.IO;

using Microsoft.Practices.EnterpriseLibrary.Data;
using System.Data.Common;

namespace EquitableGourmet
{
	public abstract class PagesBase
	{
		#region < VARIABLES >
		private int _PagesId;
		private string _PageName;
		private string _MenuName;
		private string _MenuParent;
		private int _DisplayOrder;
		private string _Icon;
		private bool _isNew;
		#endregion
		
		#region < CONSTRUCTORES >
		protected PagesBase()
		{
			_PagesId = 0;
			_PageName = string.Empty;
			_MenuName = string.Empty;
			_MenuParent = string.Empty;
			_DisplayOrder = 0;
			_Icon = string.Empty;
		}
		
		protected PagesBase(int PagesId) : this()
		{
			_PagesId = PagesId;
		}
	
		protected PagesBase(int PagesId, string PageName, string MenuName, string MenuParent, int DisplayOrder, string Icon) : this()
		{
			_PagesId = PagesId;
			_PageName = PageName;
			_MenuName = MenuName;
			_MenuParent = MenuParent;
			_DisplayOrder = DisplayOrder;
			_Icon = Icon;
		}

		#endregion
		
		#region < Metodos para Obtención de Detalles >

		#endregion
		
		#region < PROPIEDADES >
		
		public int PagesId
		{
			get	{ return _PagesId; }
			set	{ _PagesId = value; }
		}
		
		public string PageName
		{
			get	{ return _PageName; }
			set	{ _PageName = value; }
		}
		
		public string MenuName
		{
			get	{ return _MenuName; }
			set	{ _MenuName = value; }
		}
		
		public string MenuParent
		{
			get	{ return _MenuParent; }
			set	{ _MenuParent = value; }
		}
		
		public int DisplayOrder
		{
			get	{ return _DisplayOrder; }
			set	{ _DisplayOrder = value; }
		}
		
		public string Icon
		{
			get	{ return _Icon; }
			set	{ _Icon = value; }
		}
		
		public bool IsNew
		{
			get 
			{ 
				_isNew = (_PagesId == 0);
				return _isNew; 
			}
			set { _isNew = value; }
		}
		#endregion		

		#region Utilerias
		public static bool Existe(int PagesId)
		{
			Database db = DatabaseFactory.CreateDatabase();
			string sqlCommand = "daab_ExistsPages";
			DbCommand dbCommandWrapper = db.GetStoredProcCommand(sqlCommand);

			// Add in parameters
			db.AddInParameter(dbCommandWrapper, "@PagesId", DbType.Int32, PagesId);

			// DataSet that will hold the returned results		
			// Note: connection closed by ExecuteDataSet method call 
			bool ret = false;
			int num = Convert.ToInt32(db.ExecuteScalar(dbCommandWrapper));
			ret = num > 0;
			return ret;
		}
		
		public static DataTable GetAllPages()
		{
			Database db = DatabaseFactory.CreateDatabase();

			string sqlCommand = "daab_GetAllPages";
			DbCommand dbCommandWrapper = db.GetStoredProcCommand(sqlCommand);
			DataTable ret = db.ExecuteDataSet(dbCommandWrapper).Tables[0];
			
            ret.PrimaryKey = new DataColumn[] { ret.Columns["PagesId"] };
			
            return ret;
		}
		
		public static void SaveAll(DataTable tabla)
		{
			Database db = DatabaseFactory.CreateDatabase();
			DbDataAdapter da = db.GetDataAdapter();
			
			da.SelectCommand = db.GetStoredProcCommand("daab_GetAllPages");
            da.InsertCommand = db.GetStoredProcCommand("daab_AddPages");
            da.UpdateCommand = db.GetStoredProcCommand("daab_UpdatePages");
            da.DeleteCommand = db.GetStoredProcCommand("daab_DeletePages");
			
			#region Parametros de InsertCommand
			db.AddOutParameter(da.InsertCommand, "@PagesId", DbType.Int32, 4);
			db.AddInParameter(da.InsertCommand, "@PageName", DbType.String, "PageName", DataRowVersion.Default);
			db.AddInParameter(da.InsertCommand, "@MenuName", DbType.String, "MenuName", DataRowVersion.Default);
			db.AddInParameter(da.InsertCommand, "@MenuParent", DbType.String, "MenuParent", DataRowVersion.Default);
			db.AddInParameter(da.InsertCommand, "@DisplayOrder", DbType.Int32, "DisplayOrder", DataRowVersion.Default);
			db.AddInParameter(da.InsertCommand, "@Icon", DbType.String, "Icon", DataRowVersion.Default);

			#endregion
			
			#region Parametros de UpdateCommand
			db.AddInParameter(da.UpdateCommand, "@PagesId", DbType.Int32, "PagesId", DataRowVersion.Default);
			db.AddInParameter(da.UpdateCommand, "@PageName", DbType.String, "PageName", DataRowVersion.Default);
			db.AddInParameter(da.UpdateCommand, "@MenuName", DbType.String, "MenuName", DataRowVersion.Default);
			db.AddInParameter(da.UpdateCommand, "@MenuParent", DbType.String, "MenuParent", DataRowVersion.Default);
			db.AddInParameter(da.UpdateCommand, "@DisplayOrder", DbType.Int32, "DisplayOrder", DataRowVersion.Default);
			db.AddInParameter(da.UpdateCommand, "@Icon", DbType.String, "Icon", DataRowVersion.Default);

			#endregion
			
			#region Parametros de DeleteCommand
			db.AddInParameter(da.DeleteCommand, "@PagesId", DbType.Int32, "PagesId", DataRowVersion.Default);

			#endregion

			db.UpdateDataSet(tabla.DataSet, tabla.TableName, da.InsertCommand, da.UpdateCommand, da.DeleteCommand, UpdateBehavior.Standard);
		}
		#endregion

		/// <summary>
		/// Populates a dataset with info from the database, based on the requested primary key.
		/// </summary>
		/// <param name="PagesId"></param>
		/// <returns>A DataSet containing the results of the query</returns>
		private DataSet LoadByPrimaryKey(int PagesId)
		{
			// Create the Database object, using the default database service. The
			// default database service is determined through configuration.
			Database db = DatabaseFactory.CreateDatabase();

			string sqlCommand = "daab_GetPages";
			DbCommand dbCommandWrapper = db.GetStoredProcCommand(sqlCommand);

			// Add in parameters
			db.AddInParameter(dbCommandWrapper, "@PagesId", DbType.Int32, PagesId);

			// DataSet that will hold the returned results		
			// Note: connection closed by ExecuteDataSet method call 
			return db.ExecuteDataSet(dbCommandWrapper);
		}
	
		/// <summary>
		/// Populates current instance of the object with info from the database, based on the requested primary key.
		/// </summary>
		/// <param name="PagesId"></param>
		public virtual void Load(int PagesId)
		{
			// DataSet that will hold the returned results		
			DataSet ds = this.LoadByPrimaryKey(PagesId);
			
			// Load member variables from datarow
			DataRow row = ds.Tables[0].Rows[0];
			_PagesId = (int)row["PagesId"];
			_PageName = row.IsNull("PageName") ? string.Empty : (string)row["PageName"];
			_MenuName = row.IsNull("MenuName") ? string.Empty : (string)row["MenuName"];
			_MenuParent = row.IsNull("MenuParent") ? string.Empty : (string)row["MenuParent"];
			_DisplayOrder = row.IsNull("DisplayOrder") ? 0 : (int)row["DisplayOrder"];
			_Icon = row.IsNull("Icon") ? string.Empty : (string)row["Icon"];
		}

		/// <summary>
		/// Adds or updates information in the database depending on the primary key stored in the object instance.
		/// </summary>
		/// <returns>Returns True if saved successfully, False otherwise.</returns>
		public bool Save()
		{
			if (this.IsNew)
				return Insert();
			else
				return Update();
		}

		/// <summary>
		/// Inserts the current instance data into the database.
		/// </summary>
		/// <returns>Returns True if saved successfully, False otherwise.</returns>
		private bool Insert()
		{
			// Create the Database object, using the default database service. The
			// default database service is determined through configuration.
			Database db = DatabaseFactory.CreateDatabase();

			string sqlCommand = "daab_AddPages";
			DbCommand dbCommandWrapper = db.GetStoredProcCommand(sqlCommand);

			// Add parameters
			db.AddOutParameter(dbCommandWrapper, "@PagesId", DbType.Int32, 4);
			db.AddInParameter(dbCommandWrapper, "@PageName", DbType.String, SetNullValue((_PageName == string.Empty), _PageName));
			db.AddInParameter(dbCommandWrapper, "@MenuName", DbType.String, SetNullValue((_MenuName == string.Empty), _MenuName));
			db.AddInParameter(dbCommandWrapper, "@MenuParent", DbType.String, SetNullValue((_MenuParent == string.Empty), _MenuParent));
			db.AddInParameter(dbCommandWrapper, "@DisplayOrder", DbType.Int32, SetNullValue((_DisplayOrder == 0), _DisplayOrder));
			db.AddInParameter(dbCommandWrapper, "@Icon", DbType.String, SetNullValue((_Icon == string.Empty), _Icon));

			db.ExecuteNonQuery(dbCommandWrapper);
			
			// Save output parameter values
			object param;
			param = db.GetParameterValue(dbCommandWrapper, "@PagesId");
			if (param == DBNull.Value) return false;
			_PagesId = (int)param;
			
			return true;
		}

		/// <summary>
		/// Updates the current instance data in the database.
		/// </summary>
		/// <returns>Returns True if saved successfully, False otherwise.</returns>
		public bool Update()
		{
			// Create the Database object, using the default database service. The
			// default database service is determined through configuration.
			Database db = DatabaseFactory.CreateDatabase();

			string sqlCommand = "daab_UpdatePages";
			DbCommand dbCommandWrapper = db.GetStoredProcCommand(sqlCommand);

			// Add parameters
			db.AddInParameter(dbCommandWrapper, "@PagesId", DbType.Int32, _PagesId);
			db.AddInParameter(dbCommandWrapper, "@PageName", DbType.String, SetNullValue((_PageName == string.Empty), _PageName));
			db.AddInParameter(dbCommandWrapper, "@MenuName", DbType.String, SetNullValue((_MenuName == string.Empty), _MenuName));
			db.AddInParameter(dbCommandWrapper, "@MenuParent", DbType.String, SetNullValue((_MenuParent == string.Empty), _MenuParent));
			db.AddInParameter(dbCommandWrapper, "@DisplayOrder", DbType.Int32, SetNullValue((_DisplayOrder == 0), _DisplayOrder));
			db.AddInParameter(dbCommandWrapper, "@Icon", DbType.String, SetNullValue((_Icon == string.Empty), _Icon));

			try
			{
				db.ExecuteNonQuery(dbCommandWrapper);
				
				// Save output parameter values
				object param;
				param = db.GetParameterValue(dbCommandWrapper, "@PagesId");
				if (param == DBNull.Value) return false;
				_PagesId = (int)param;
				
				return true;
			}
			catch
			{
				return false;
			}
		}

		/// <summary>
		/// Removes info from the database, based on the requested primary key.
		/// </summary>
		/// <param name="PagesId"></param>
		public static void Remove(int PagesId)
		{
			// Create the Database object, using the default database service. The
			// default database service is determined through configuration.
			Database db = DatabaseFactory.CreateDatabase();

			string sqlCommand = "daab_DeletePages";
			DbCommand dbCommandWrapper = db.GetStoredProcCommand(sqlCommand);

			// Add primary keys to command wrapper.
			db.AddInParameter(dbCommandWrapper, "@PagesId", DbType.Int32, PagesId);

			db.ExecuteNonQuery(dbCommandWrapper);
		}
		
		/// <summary>
		/// Serializes the current instance data to an Xml string.
		/// </summary>
		/// <returns>A string containing the Xml representation of the object.</returns>
		virtual public string ToXml()
		{
			// DataSet that will hold the returned results		
			DataSet ds = this.LoadByPrimaryKey(_PagesId);
			StringWriter writer = new StringWriter(); 
			ds.WriteXml(writer); 
			return writer.ToString(); 
		}

		/// <summary>
		/// Utility function that returns a DBNull.Value if requested. The comparison is done inline
		/// in the Insert() and Update() functions.
		/// </summary>
		private object SetNullValue(bool isNullValue, object value)
		{
			if (isNullValue)
				return DBNull.Value;
			else
				return value;
		}
	}
}
