/*
'===============================================================================
'  Generated From - CSharp_DAAB_BusinessEntity.vbgen
' 
'  ** IMPORTANT  ** 
'  How to Generate your stored procedures:
' 
'  SQL      = SQL_DAAB_Net2_StoredProcs.vbgen
'  
'  This object is 'abstract' which means you need to inherit from it to be able
'  to instantiate it.  This is very easily done. You can override properties and
'  methods in your derived class, this allows you to regenerate this class at any
'  time and not worry about overwriting custom code. 
'
'  NEVER EDIT THIS FILE.
'
'  public class YourObject :  YourObjectBase
'  {
'
'  }
'
'===============================================================================
*/

// Generated by MyGeneration Version # (1.3.0.3)

using System;
using System.Data;
using System.Configuration;
using System.Collections;
using System.Collections.Specialized;
using System.Xml;
using System.IO;

using Microsoft.Practices.EnterpriseLibrary.Data;
using System.Data.Common;

namespace EquitableGourmet
{
	public abstract class PromotionBase
	{
		#region < VARIABLES >
		private int _PromotionID;
		private string _Number;
		private string _Name;
		private string _Description;
		private DateTime _StartDate;
		private DateTime _EndDate;
		private int _PromotionStatusID;
		private double _Total;
		private DateTime _CreatedOn;
		private int _CreatedBy;
		private bool _Del;
		private bool _isNew;
		#endregion
		
		#region < CONSTRUCTORES >
		protected PromotionBase()
		{
			_PromotionID = 0;
			_Number = string.Empty;
			_Name = string.Empty;
			_Description = string.Empty;
			_StartDate = DateTime.Parse("01/01/1900");
			_EndDate = DateTime.Parse("01/01/1900");
			_PromotionStatusID = 0;
			_Total = 0;
			_CreatedOn = DateTime.Parse("01/01/1900");
			_CreatedBy = 0;
			_Del = false;
		}
		
		protected PromotionBase(int PromotionID) : this()
		{
			_PromotionID = PromotionID;
		}
	
		protected PromotionBase(int PromotionID, string Number, string Name, string Description, DateTime StartDate, DateTime EndDate, int PromotionStatusID, double Total, DateTime CreatedOn, int CreatedBy, bool Del) : this()
		{
			_PromotionID = PromotionID;
			_Number = Number;
			_Name = Name;
			_Description = Description;
			_StartDate = StartDate;
			_EndDate = EndDate;
			_PromotionStatusID = PromotionStatusID;
			_Total = Total;
			_CreatedOn = CreatedOn;
			_CreatedBy = CreatedBy;
			_Del = Del;
		}

		#endregion
		
		#region < Metodos para Obtención de Detalles >

		#endregion
		
		#region < PROPIEDADES >
		
		public int PromotionID
		{
			get	{ return _PromotionID; }
			set	{ _PromotionID = value; }
		}
		
		public string Number
		{
			get	{ return _Number; }
			set	{ _Number = value; }
		}
		
		public string Name
		{
			get	{ return _Name; }
			set	{ _Name = value; }
		}
		
		public string Description
		{
			get	{ return _Description; }
			set	{ _Description = value; }
		}
		
		public DateTime StartDate
		{
			get	{ return _StartDate; }
			set	{ _StartDate = value; }
		}
		
		public DateTime EndDate
		{
			get	{ return _EndDate; }
			set	{ _EndDate = value; }
		}
		
		public int PromotionStatusID
		{
			get	{ return _PromotionStatusID; }
			set	{ _PromotionStatusID = value; }
		}
		
		public double Total
		{
			get	{ return _Total; }
			set	{ _Total = value; }
		}
		
		public DateTime CreatedOn
		{
			get	{ return _CreatedOn; }
			set	{ _CreatedOn = value; }
		}
		
		public int CreatedBy
		{
			get	{ return _CreatedBy; }
			set	{ _CreatedBy = value; }
		}
		
		public bool Del
		{
			get	{ return _Del; }
			set	{ _Del = value; }
		}
		
		public bool IsNew
		{
			get 
			{ 
				return _isNew; 
			}
			set { _isNew = value; }
		}
		#endregion		

		#region Utilerias
		public static bool Existe(int PromotionID)
		{
			Database db = DatabaseFactory.CreateDatabase();
			string sqlCommand = "daab_ExistsPromotion";
			DbCommand dbCommandWrapper = db.GetStoredProcCommand(sqlCommand);

			// Add in parameters
			db.AddInParameter(dbCommandWrapper, "@PromotionID", DbType.Int32, PromotionID);

			// DataSet that will hold the returned results		
			// Note: connection closed by ExecuteDataSet method call 
			bool ret = false;
			int num = Convert.ToInt32(db.ExecuteScalar(dbCommandWrapper));
			ret = num > 0;
			return ret;
		}
		
		public static DataTable GetAllPromotion()
		{
			Database db = DatabaseFactory.CreateDatabase();

			string sqlCommand = "daab_GetAllPromotion";
			DbCommand dbCommandWrapper = db.GetStoredProcCommand(sqlCommand);
			DataTable ret = db.ExecuteDataSet(dbCommandWrapper).Tables[0];
			
            ret.PrimaryKey = new DataColumn[] { ret.Columns["PromotionID"] };
			
            return ret;
		}
		
		public static void SaveAll(DataTable tabla)
		{
			Database db = DatabaseFactory.CreateDatabase();
			DbDataAdapter da = db.GetDataAdapter();
			
			da.SelectCommand = db.GetStoredProcCommand("daab_GetAllPromotion");
            da.InsertCommand = db.GetStoredProcCommand("daab_AddPromotion");
            da.UpdateCommand = db.GetStoredProcCommand("daab_UpdatePromotion");
            da.DeleteCommand = db.GetStoredProcCommand("daab_DeletePromotion");
			
			#region Parametros de InsertCommand
			db.AddInParameter(da.InsertCommand, "@PromotionID", DbType.Int32, "PromotionID", DataRowVersion.Default);
			db.AddInParameter(da.InsertCommand, "@Number", DbType.String, "Number", DataRowVersion.Default);
			db.AddInParameter(da.InsertCommand, "@Name", DbType.String, "Name", DataRowVersion.Default);
			db.AddInParameter(da.InsertCommand, "@Description", DbType.String, "Description", DataRowVersion.Default);
			db.AddInParameter(da.InsertCommand, "@StartDate", DbType.DateTime, "StartDate", DataRowVersion.Default);
			db.AddInParameter(da.InsertCommand, "@EndDate", DbType.DateTime, "EndDate", DataRowVersion.Default);
			db.AddInParameter(da.InsertCommand, "@PromotionStatusID", DbType.Int32, "PromotionStatusID", DataRowVersion.Default);
			db.AddInParameter(da.InsertCommand, "@Total", DbType.Double, "Total", DataRowVersion.Default);
			db.AddInParameter(da.InsertCommand, "@CreatedOn", DbType.DateTime, "CreatedOn", DataRowVersion.Default);
			db.AddInParameter(da.InsertCommand, "@CreatedBy", DbType.Int32, "CreatedBy", DataRowVersion.Default);
			db.AddInParameter(da.InsertCommand, "@Del", DbType.Boolean, "Del", DataRowVersion.Default);

			#endregion
			
			#region Parametros de UpdateCommand
			db.AddInParameter(da.UpdateCommand, "@PromotionID", DbType.Int32, "PromotionID", DataRowVersion.Default);
			db.AddInParameter(da.UpdateCommand, "@Number", DbType.String, "Number", DataRowVersion.Default);
			db.AddInParameter(da.UpdateCommand, "@Name", DbType.String, "Name", DataRowVersion.Default);
			db.AddInParameter(da.UpdateCommand, "@Description", DbType.String, "Description", DataRowVersion.Default);
			db.AddInParameter(da.UpdateCommand, "@StartDate", DbType.DateTime, "StartDate", DataRowVersion.Default);
			db.AddInParameter(da.UpdateCommand, "@EndDate", DbType.DateTime, "EndDate", DataRowVersion.Default);
			db.AddInParameter(da.UpdateCommand, "@PromotionStatusID", DbType.Int32, "PromotionStatusID", DataRowVersion.Default);
			db.AddInParameter(da.UpdateCommand, "@Total", DbType.Double, "Total", DataRowVersion.Default);
			db.AddInParameter(da.UpdateCommand, "@CreatedOn", DbType.DateTime, "CreatedOn", DataRowVersion.Default);
			db.AddInParameter(da.UpdateCommand, "@CreatedBy", DbType.Int32, "CreatedBy", DataRowVersion.Default);
			db.AddInParameter(da.UpdateCommand, "@Del", DbType.Boolean, "Del", DataRowVersion.Default);

			#endregion
			
			#region Parametros de DeleteCommand
			db.AddInParameter(da.DeleteCommand, "@PromotionID", DbType.Int32, "PromotionID", DataRowVersion.Default);

			#endregion

			db.UpdateDataSet(tabla.DataSet, tabla.TableName, da.InsertCommand, da.UpdateCommand, da.DeleteCommand, UpdateBehavior.Standard);
		}
		#endregion

		/// <summary>
		/// Populates a dataset with info from the database, based on the requested primary key.
		/// </summary>
		/// <param name="PromotionID"></param>
		/// <returns>A DataSet containing the results of the query</returns>
		private DataSet LoadByPrimaryKey(int PromotionID)
		{
			// Create the Database object, using the default database service. The
			// default database service is determined through configuration.
			Database db = DatabaseFactory.CreateDatabase();

			string sqlCommand = "daab_GetPromotion";
			DbCommand dbCommandWrapper = db.GetStoredProcCommand(sqlCommand);

			// Add in parameters
			db.AddInParameter(dbCommandWrapper, "@PromotionID", DbType.Int32, PromotionID);

			// DataSet that will hold the returned results		
			// Note: connection closed by ExecuteDataSet method call 
			return db.ExecuteDataSet(dbCommandWrapper);
		}
	
		/// <summary>
		/// Populates current instance of the object with info from the database, based on the requested primary key.
		/// </summary>
		/// <param name="PromotionID"></param>
		public virtual void Load(int PromotionID)
		{
			// DataSet that will hold the returned results		
			DataSet ds = this.LoadByPrimaryKey(PromotionID);
			
			// Load member variables from datarow
			DataRow row = ds.Tables[0].Rows[0];
			_PromotionID = (int)row["PromotionID"];
			_Number = row.IsNull("Number") ? string.Empty : (string)row["Number"];
			_Name = row.IsNull("Name") ? string.Empty : (string)row["Name"];
			_Description = row.IsNull("Description") ? string.Empty : (string)row["Description"];
			_StartDate = row.IsNull("StartDate") ? DateTime.Parse("01/01/1900") : (DateTime)row["StartDate"];
			_EndDate = row.IsNull("EndDate") ? DateTime.Parse("01/01/1900") : (DateTime)row["EndDate"];
			_PromotionStatusID = row.IsNull("PromotionStatusID") ? 0 : (int)row["PromotionStatusID"];
			_Total = row.IsNull("Total") ? 0 : (double)row["Total"];
			_CreatedOn = row.IsNull("CreatedOn") ? DateTime.Parse("01/01/1900") : (DateTime)row["CreatedOn"];
			_CreatedBy = row.IsNull("CreatedBy") ? 0 : (int)row["CreatedBy"];
			_Del = row.IsNull("Del") ? false : (bool)row["Del"];
		}

		/// <summary>
		/// Adds or updates information in the database depending on the primary key stored in the object instance.
		/// </summary>
		/// <returns>Returns True if saved successfully, False otherwise.</returns>
		public bool Save()
		{
			if (this.IsNew)
				return Insert();
			else
				return Update();
		}

		/// <summary>
		/// Inserts the current instance data into the database.
		/// </summary>
		/// <returns>Returns True if saved successfully, False otherwise.</returns>
		private bool Insert()
		{
			// Create the Database object, using the default database service. The
			// default database service is determined through configuration.
			Database db = DatabaseFactory.CreateDatabase();

			string sqlCommand = "daab_AddPromotion";
			DbCommand dbCommandWrapper = db.GetStoredProcCommand(sqlCommand);

			// Add parameters
			db.AddInParameter(dbCommandWrapper, "@PromotionID", DbType.Int32, _PromotionID);
			db.AddInParameter(dbCommandWrapper, "@Number", DbType.String, SetNullValue((_Number == string.Empty), _Number));
			db.AddInParameter(dbCommandWrapper, "@Name", DbType.String, SetNullValue((_Name == string.Empty), _Name));
			db.AddInParameter(dbCommandWrapper, "@Description", DbType.String, SetNullValue((_Description == string.Empty), _Description));
			db.AddInParameter(dbCommandWrapper, "@StartDate", DbType.DateTime, SetNullValue((_StartDate == DateTime.Parse("01/01/1900")), _StartDate));
			db.AddInParameter(dbCommandWrapper, "@EndDate", DbType.DateTime, SetNullValue((_EndDate == DateTime.Parse("01/01/1900")), _EndDate));
			db.AddInParameter(dbCommandWrapper, "@PromotionStatusID", DbType.Int32, SetNullValue((_PromotionStatusID == 0), _PromotionStatusID));
			db.AddInParameter(dbCommandWrapper, "@Total", DbType.Double, SetNullValue((_Total == 0), _Total));
			db.AddInParameter(dbCommandWrapper, "@CreatedOn", DbType.DateTime, SetNullValue((_CreatedOn == DateTime.Parse("01/01/1900")), _CreatedOn));
			db.AddInParameter(dbCommandWrapper, "@CreatedBy", DbType.Int32, SetNullValue((_CreatedBy == 0), _CreatedBy));
            db.AddInParameter(dbCommandWrapper, "@Del", DbType.Boolean, SetNullValue((_Del == true), _Del));

			db.ExecuteNonQuery(dbCommandWrapper);
			
			return true;
		}

		/// <summary>
		/// Updates the current instance data in the database.
		/// </summary>
		/// <returns>Returns True if saved successfully, False otherwise.</returns>
		public bool Update()
		{
			// Create the Database object, using the default database service. The
			// default database service is determined through configuration.
			Database db = DatabaseFactory.CreateDatabase();

			string sqlCommand = "daab_UpdatePromotion";
			DbCommand dbCommandWrapper = db.GetStoredProcCommand(sqlCommand);

			// Add parameters
			db.AddInParameter(dbCommandWrapper, "@PromotionID", DbType.Int32, _PromotionID);
			db.AddInParameter(dbCommandWrapper, "@Number", DbType.String, SetNullValue((_Number == string.Empty), _Number));
			db.AddInParameter(dbCommandWrapper, "@Name", DbType.String, SetNullValue((_Name == string.Empty), _Name));
			db.AddInParameter(dbCommandWrapper, "@Description", DbType.String, SetNullValue((_Description == string.Empty), _Description));
			db.AddInParameter(dbCommandWrapper, "@StartDate", DbType.DateTime, SetNullValue((_StartDate == DateTime.Parse("01/01/1900")), _StartDate));
			db.AddInParameter(dbCommandWrapper, "@EndDate", DbType.DateTime, SetNullValue((_EndDate == DateTime.Parse("01/01/1900")), _EndDate));
			db.AddInParameter(dbCommandWrapper, "@PromotionStatusID", DbType.Int32, SetNullValue((_PromotionStatusID == 0), _PromotionStatusID));
			db.AddInParameter(dbCommandWrapper, "@Total", DbType.Double, SetNullValue((_Total == 0), _Total));
			db.AddInParameter(dbCommandWrapper, "@CreatedOn", DbType.DateTime, SetNullValue((_CreatedOn == DateTime.Parse("01/01/1900")), _CreatedOn));
			db.AddInParameter(dbCommandWrapper, "@CreatedBy", DbType.Int32, SetNullValue((_CreatedBy == 0), _CreatedBy));
			db.AddInParameter(dbCommandWrapper, "@Del", DbType.Boolean, SetNullValue((_Del == false), _Del));

			try
			{
				db.ExecuteNonQuery(dbCommandWrapper);
				
				return true;
			}
			catch
			{
				return false;
			}
		}

		/// <summary>
		/// Removes info from the database, based on the requested primary key.
		/// </summary>
		/// <param name="PromotionID"></param>
		public static void Remove(int PromotionID)
		{
			// Create the Database object, using the default database service. The
			// default database service is determined through configuration.
			Database db = DatabaseFactory.CreateDatabase();

			string sqlCommand = "daab_DeletePromotion";
			DbCommand dbCommandWrapper = db.GetStoredProcCommand(sqlCommand);

			// Add primary keys to command wrapper.
			db.AddInParameter(dbCommandWrapper, "@PromotionID", DbType.Int32, PromotionID);

			db.ExecuteNonQuery(dbCommandWrapper);
		}
		
		/// <summary>
		/// Serializes the current instance data to an Xml string.
		/// </summary>
		/// <returns>A string containing the Xml representation of the object.</returns>
		virtual public string ToXml()
		{
			// DataSet that will hold the returned results		
			DataSet ds = this.LoadByPrimaryKey(_PromotionID);
			StringWriter writer = new StringWriter(); 
			ds.WriteXml(writer); 
			return writer.ToString(); 
		}

		/// <summary>
		/// Utility function that returns a DBNull.Value if requested. The comparison is done inline
		/// in the Insert() and Update() functions.
		/// </summary>
		private object SetNullValue(bool isNullValue, object value)
		{
			if (isNullValue)
				return DBNull.Value;
			else
				return value;
		}
	}
}
