
// Generated by MyGeneration Version # (1.3.0.3)

using System;
using System.Data.Common;
using System.Data;
using Microsoft.Practices.EnterpriseLibrary.Data;

namespace EquitableGourmet
{
	public class ResetPassword : ResetPasswordBase
	{
		#region < CONSTRUCTORES >
		
		public ResetPassword() : base()	{}
		
		#endregion



        public static DataTable ValidateCode(String Code)
        {
            Database db = DatabaseFactory.CreateDatabase();
            string sqlCommand = "ValidateCode";
            DbCommand dbCommandWrapper = db.GetStoredProcCommand(sqlCommand);
            db.AddInParameter(dbCommandWrapper, "@Code", DbType.String, Code);
            DataSet ds = db.ExecuteDataSet(dbCommandWrapper);

            DataTable dt = ds.Tables[0];

            return dt;


        }
	}
}
