/*
'===============================================================================
'  Generated From - CSharp_DAAB_BusinessEntity.vbgen
' 
'  ** IMPORTANT  ** 
'  How to Generate your stored procedures:
' 
'  SQL      = SQL_DAAB_Net2_StoredProcs.vbgen
'  
'  This object is 'abstract' which means you need to inherit from it to be able
'  to instantiate it.  This is very easily done. You can override properties and
'  methods in your derived class, this allows you to regenerate this class at any
'  time and not worry about overwriting custom code. 
'
'  NEVER EDIT THIS FILE.
'
'  public class YourObject :  YourObjectBase
'  {
'
'  }
'
'===============================================================================
*/

// Generated by MyGeneration Version # (1.3.0.3)

using System;
using System.Data;
using System.Configuration;
using System.Collections;
using System.Collections.Specialized;
using System.Xml;
using System.IO;

using Microsoft.Practices.EnterpriseLibrary.Data;
using System.Data.Common;

namespace EquitableGourmet
{
	public abstract class ResetPasswordBase
	{
		#region < VARIABLES >
		private int _ResetPasswordID;
		private string _Code;
		private string _Username;
		private DateTime _CreatedOn;
		private bool _IsValid;
		private bool _isNew;
		#endregion
		
		#region < CONSTRUCTORES >
		protected ResetPasswordBase()
		{
			_ResetPasswordID = 0;
			_Code = string.Empty;
			_Username = string.Empty;
			_CreatedOn = DateTime.Parse("01/01/1900");
			_IsValid = false;
		}
		
		protected ResetPasswordBase(int ResetPasswordID) : this()
		{
			_ResetPasswordID = ResetPasswordID;
		}
	
		protected ResetPasswordBase(int ResetPasswordID, string Code, string Username, DateTime CreatedOn, bool IsValid) : this()
		{
			_ResetPasswordID = ResetPasswordID;
			_Code = Code;
			_Username = Username;
			_CreatedOn = CreatedOn;
			_IsValid = IsValid;
		}

		#endregion
		
		#region < Metodos para Obtención de Detalles >

		#endregion
		
		#region < PROPIEDADES >
		
		public int ResetPasswordID
		{
			get	{ return _ResetPasswordID; }
			set	{ _ResetPasswordID = value; }
		}
		
		public string Code
		{
			get	{ return _Code; }
			set	{ _Code = value; }
		}
		
		public string Username
		{
			get	{ return _Username; }
			set	{ _Username = value; }
		}
		
		public DateTime CreatedOn
		{
			get	{ return _CreatedOn; }
			set	{ _CreatedOn = value; }
		}
		
		public bool IsValid
		{
			get	{ return _IsValid; }
			set	{ _IsValid = value; }
		}
		
		public bool IsNew
		{
			get 
			{ 
				_isNew = (_ResetPasswordID == 0);
				return _isNew; 
			}
			set { _isNew = value; }
		}
		#endregion		

		#region Utilerias
		public static bool Existe(int ResetPasswordID)
		{
			Database db = DatabaseFactory.CreateDatabase();
			string sqlCommand = "daab_ExistsResetPassword";
			DbCommand dbCommandWrapper = db.GetStoredProcCommand(sqlCommand);

			// Add in parameters
			db.AddInParameter(dbCommandWrapper, "@ResetPasswordID", DbType.Int32, ResetPasswordID);

			// DataSet that will hold the returned results		
			// Note: connection closed by ExecuteDataSet method call 
			bool ret = false;
			int num = Convert.ToInt32(db.ExecuteScalar(dbCommandWrapper));
			ret = num > 0;
			return ret;
		}
		
		public static DataTable GetAllResetPassword()
		{
			Database db = DatabaseFactory.CreateDatabase();

			string sqlCommand = "daab_GetAllResetPassword";
			DbCommand dbCommandWrapper = db.GetStoredProcCommand(sqlCommand);
			DataTable ret = db.ExecuteDataSet(dbCommandWrapper).Tables[0];
			
            ret.PrimaryKey = new DataColumn[] { ret.Columns["ResetPasswordID"] };
			
            return ret;
		}
		
		public static void SaveAll(DataTable tabla)
		{
			Database db = DatabaseFactory.CreateDatabase();
			DbDataAdapter da = db.GetDataAdapter();
			
			da.SelectCommand = db.GetStoredProcCommand("daab_GetAllResetPassword");
            da.InsertCommand = db.GetStoredProcCommand("daab_AddResetPassword");
            da.UpdateCommand = db.GetStoredProcCommand("daab_UpdateResetPassword");
            da.DeleteCommand = db.GetStoredProcCommand("daab_DeleteResetPassword");
			
			#region Parametros de InsertCommand
			db.AddOutParameter(da.InsertCommand, "@ResetPasswordID", DbType.Int32, 4);
			db.AddInParameter(da.InsertCommand, "@Code", DbType.String, "Code", DataRowVersion.Default);
			db.AddInParameter(da.InsertCommand, "@Username", DbType.String, "Username", DataRowVersion.Default);
			db.AddInParameter(da.InsertCommand, "@CreatedOn", DbType.DateTime, "CreatedOn", DataRowVersion.Default);
			db.AddInParameter(da.InsertCommand, "@IsValid", DbType.Boolean, "IsValid", DataRowVersion.Default);

			#endregion
			
			#region Parametros de UpdateCommand
			db.AddInParameter(da.UpdateCommand, "@ResetPasswordID", DbType.Int32, "ResetPasswordID", DataRowVersion.Default);
			db.AddInParameter(da.UpdateCommand, "@Code", DbType.String, "Code", DataRowVersion.Default);
			db.AddInParameter(da.UpdateCommand, "@Username", DbType.String, "Username", DataRowVersion.Default);
			db.AddInParameter(da.UpdateCommand, "@CreatedOn", DbType.DateTime, "CreatedOn", DataRowVersion.Default);
			db.AddInParameter(da.UpdateCommand, "@IsValid", DbType.Boolean, "IsValid", DataRowVersion.Default);

			#endregion
			
			#region Parametros de DeleteCommand
			db.AddInParameter(da.DeleteCommand, "@ResetPasswordID", DbType.Int32, "ResetPasswordID", DataRowVersion.Default);

			#endregion

			db.UpdateDataSet(tabla.DataSet, tabla.TableName, da.InsertCommand, da.UpdateCommand, da.DeleteCommand, UpdateBehavior.Standard);
		}
		#endregion

		/// <summary>
		/// Populates a dataset with info from the database, based on the requested primary key.
		/// </summary>
		/// <param name="ResetPasswordID"></param>
		/// <returns>A DataSet containing the results of the query</returns>
		private DataSet LoadByPrimaryKey(int ResetPasswordID)
		{
			// Create the Database object, using the default database service. The
			// default database service is determined through configuration.
			Database db = DatabaseFactory.CreateDatabase();

			string sqlCommand = "daab_GetResetPassword";
			DbCommand dbCommandWrapper = db.GetStoredProcCommand(sqlCommand);

			// Add in parameters
			db.AddInParameter(dbCommandWrapper, "@ResetPasswordID", DbType.Int32, ResetPasswordID);

			// DataSet that will hold the returned results		
			// Note: connection closed by ExecuteDataSet method call 
			return db.ExecuteDataSet(dbCommandWrapper);
		}
	
		/// <summary>
		/// Populates current instance of the object with info from the database, based on the requested primary key.
		/// </summary>
		/// <param name="ResetPasswordID"></param>
		public virtual void Load(int ResetPasswordID)
		{
			// DataSet that will hold the returned results		
			DataSet ds = this.LoadByPrimaryKey(ResetPasswordID);
			
			// Load member variables from datarow
			DataRow row = ds.Tables[0].Rows[0];
			_ResetPasswordID = (int)row["ResetPasswordID"];
			_Code = row.IsNull("Code") ? string.Empty : (string)row["Code"];
			_Username = row.IsNull("Username") ? string.Empty : (string)row["Username"];
			_CreatedOn = row.IsNull("CreatedOn") ? DateTime.Parse("01/01/1900") : (DateTime)row["CreatedOn"];
			_IsValid = row.IsNull("IsValid") ? false : (bool)row["IsValid"];
		}

		/// <summary>
		/// Adds or updates information in the database depending on the primary key stored in the object instance.
		/// </summary>
		/// <returns>Returns True if saved successfully, False otherwise.</returns>
		public bool Save()
		{
			if (this.IsNew)
				return Insert();
			else
				return Update();
		}

		/// <summary>
		/// Inserts the current instance data into the database.
		/// </summary>
		/// <returns>Returns True if saved successfully, False otherwise.</returns>
		private bool Insert()
		{
			// Create the Database object, using the default database service. The
			// default database service is determined through configuration.
			Database db = DatabaseFactory.CreateDatabase();

			string sqlCommand = "daab_AddResetPassword";
			DbCommand dbCommandWrapper = db.GetStoredProcCommand(sqlCommand);

			// Add parameters
			db.AddOutParameter(dbCommandWrapper, "@ResetPasswordID", DbType.Int32, 4);
			db.AddInParameter(dbCommandWrapper, "@Code", DbType.String, SetNullValue((_Code == string.Empty), _Code));
			db.AddInParameter(dbCommandWrapper, "@Username", DbType.String, SetNullValue((_Username == string.Empty), _Username));
			db.AddInParameter(dbCommandWrapper, "@CreatedOn", DbType.DateTime, SetNullValue((_CreatedOn == DateTime.Parse("01/01/1900")), _CreatedOn));
            db.AddInParameter(dbCommandWrapper, "@IsValid", DbType.Boolean, SetNullValue((_IsValid == true), _IsValid));

			db.ExecuteNonQuery(dbCommandWrapper);
			
			// Save output parameter values
			object param;
			param = db.GetParameterValue(dbCommandWrapper, "@ResetPasswordID");
			if (param == DBNull.Value) return false;
			_ResetPasswordID = (int)param;
			
			return true;
		}

		/// <summary>
		/// Updates the current instance data in the database.
		/// </summary>
		/// <returns>Returns True if saved successfully, False otherwise.</returns>
		public bool Update()
		{
			// Create the Database object, using the default database service. The
			// default database service is determined through configuration.
			Database db = DatabaseFactory.CreateDatabase();

			string sqlCommand = "daab_UpdateResetPassword";
			DbCommand dbCommandWrapper = db.GetStoredProcCommand(sqlCommand);

			// Add parameters
			db.AddInParameter(dbCommandWrapper, "@ResetPasswordID", DbType.Int32, _ResetPasswordID);
			db.AddInParameter(dbCommandWrapper, "@Code", DbType.String, SetNullValue((_Code == string.Empty), _Code));
			db.AddInParameter(dbCommandWrapper, "@Username", DbType.String, SetNullValue((_Username == string.Empty), _Username));
			db.AddInParameter(dbCommandWrapper, "@CreatedOn", DbType.DateTime, SetNullValue((_CreatedOn == DateTime.Parse("01/01/1900")), _CreatedOn));
			db.AddInParameter(dbCommandWrapper, "@IsValid", DbType.Boolean, SetNullValue((_IsValid == false), _IsValid));

			try
			{
				db.ExecuteNonQuery(dbCommandWrapper);
				
				// Save output parameter values
				object param;
				param = db.GetParameterValue(dbCommandWrapper, "@ResetPasswordID");
				if (param == DBNull.Value) return false;
				_ResetPasswordID = (int)param;
				
				return true;
			}
			catch
			{
				return false;
			}
		}

		/// <summary>
		/// Removes info from the database, based on the requested primary key.
		/// </summary>
		/// <param name="ResetPasswordID"></param>
		public static void Remove(int ResetPasswordID)
		{
			// Create the Database object, using the default database service. The
			// default database service is determined through configuration.
			Database db = DatabaseFactory.CreateDatabase();

			string sqlCommand = "daab_DeleteResetPassword";
			DbCommand dbCommandWrapper = db.GetStoredProcCommand(sqlCommand);

			// Add primary keys to command wrapper.
			db.AddInParameter(dbCommandWrapper, "@ResetPasswordID", DbType.Int32, ResetPasswordID);

			db.ExecuteNonQuery(dbCommandWrapper);
		}
		
		/// <summary>
		/// Serializes the current instance data to an Xml string.
		/// </summary>
		/// <returns>A string containing the Xml representation of the object.</returns>
		virtual public string ToXml()
		{
			// DataSet that will hold the returned results		
			DataSet ds = this.LoadByPrimaryKey(_ResetPasswordID);
			StringWriter writer = new StringWriter(); 
			ds.WriteXml(writer); 
			return writer.ToString(); 
		}

		/// <summary>
		/// Utility function that returns a DBNull.Value if requested. The comparison is done inline
		/// in the Insert() and Update() functions.
		/// </summary>
		private object SetNullValue(bool isNullValue, object value)
		{
			if (isNullValue)
				return DBNull.Value;
			else
				return value;
		}
	}
}
