/*
'===============================================================================
'  Generated From - CSharp_DAAB_BusinessEntity.vbgen
' 
'  ** IMPORTANT  ** 
'  How to Generate your stored procedures:
' 
'  SQL      = SQL_DAAB_Net2_StoredProcs.vbgen
'  
'  This object is 'abstract' which means you need to inherit from it to be able
'  to instantiate it.  This is very easily done. You can override properties and
'  methods in your derived class, this allows you to regenerate this class at any
'  time and not worry about overwriting custom code. 
'
'  NEVER EDIT THIS FILE.
'
'  public class YourObject :  YourObjectBase
'  {
'
'  }
'
'===============================================================================
*/

// Generated by MyGeneration Version # (1.3.0.3)

using System;
using System.Data;
using System.Configuration;
using System.Collections;
using System.Collections.Specialized;
using System.Xml;
using System.IO;

using Microsoft.Practices.EnterpriseLibrary.Data;
using System.Data.Common;

namespace EquitableGourmet
{
	public abstract class UserTypeBase
	{
		#region < VARIABLES >
		private int _UserTypeID;
		private string _Name;
		private bool _IsBuyer;
		private bool _IsAdPlacer;
		private bool _IsJobPlacer;
		private bool _Del;
		private bool _isNew;
		#endregion
		
		#region < CONSTRUCTORES >
		protected UserTypeBase()
		{
			_UserTypeID = 0;
			_Name = string.Empty;
			_IsBuyer = false;
			_IsAdPlacer = false;
			_IsJobPlacer = false;
			_Del = false;
		}
		
		protected UserTypeBase(int UserTypeID) : this()
		{
			_UserTypeID = UserTypeID;
		}
	
		protected UserTypeBase(int UserTypeID, string Name, bool IsBuyer, bool IsAdPlacer, bool IsJobPlacer, bool Del) : this()
		{
			_UserTypeID = UserTypeID;
			_Name = Name;
			_IsBuyer = IsBuyer;
			_IsAdPlacer = IsAdPlacer;
			_IsJobPlacer = IsJobPlacer;
			_Del = Del;
		}

		#endregion
		
		#region < Metodos para Obtención de Detalles >

		#endregion
		
		#region < PROPIEDADES >
		
		public int UserTypeID
		{
			get	{ return _UserTypeID; }
			set	{ _UserTypeID = value; }
		}
		
		public string Name
		{
			get	{ return _Name; }
			set	{ _Name = value; }
		}
		
		public bool IsBuyer
		{
			get	{ return _IsBuyer; }
			set	{ _IsBuyer = value; }
		}
		
		public bool IsAdPlacer
		{
			get	{ return _IsAdPlacer; }
			set	{ _IsAdPlacer = value; }
		}
		
		public bool IsJobPlacer
		{
			get	{ return _IsJobPlacer; }
			set	{ _IsJobPlacer = value; }
		}
		
		public bool Del
		{
			get	{ return _Del; }
			set	{ _Del = value; }
		}
		
		public bool IsNew
		{
			get 
			{ 
				_isNew = (_UserTypeID == 0);
				return _isNew; 
			}
			set { _isNew = value; }
		}
		#endregion		

		#region Utilerias
		public static bool Existe(int UserTypeID)
		{
			Database db = DatabaseFactory.CreateDatabase();
			string sqlCommand = "daab_ExistsUserType";
			DbCommand dbCommandWrapper = db.GetStoredProcCommand(sqlCommand);

			// Add in parameters
			db.AddInParameter(dbCommandWrapper, "@UserTypeID", DbType.Int32, UserTypeID);

			// DataSet that will hold the returned results		
			// Note: connection closed by ExecuteDataSet method call 
			bool ret = false;
			int num = Convert.ToInt32(db.ExecuteScalar(dbCommandWrapper));
			ret = num > 0;
			return ret;
		}
		
		public static DataTable GetAllUserType()
		{
			Database db = DatabaseFactory.CreateDatabase();

			string sqlCommand = "daab_GetAllUserType";
			DbCommand dbCommandWrapper = db.GetStoredProcCommand(sqlCommand);
			DataTable ret = db.ExecuteDataSet(dbCommandWrapper).Tables[0];
			
            ret.PrimaryKey = new DataColumn[] { ret.Columns["UserTypeID"] };
			
            return ret;
		}
		
		public static void SaveAll(DataTable tabla)
		{
			Database db = DatabaseFactory.CreateDatabase();
			DbDataAdapter da = db.GetDataAdapter();
			
			da.SelectCommand = db.GetStoredProcCommand("daab_GetAllUserType");
            da.InsertCommand = db.GetStoredProcCommand("daab_AddUserType");
            da.UpdateCommand = db.GetStoredProcCommand("daab_UpdateUserType");
            da.DeleteCommand = db.GetStoredProcCommand("daab_DeleteUserType");
			
			#region Parametros de InsertCommand
			db.AddOutParameter(da.InsertCommand, "@UserTypeID", DbType.Int32, 4);
			db.AddInParameter(da.InsertCommand, "@Name", DbType.String, "Name", DataRowVersion.Default);
			db.AddInParameter(da.InsertCommand, "@IsBuyer", DbType.Boolean, "IsBuyer", DataRowVersion.Default);
			db.AddInParameter(da.InsertCommand, "@IsAdPlacer", DbType.Boolean, "IsAdPlacer", DataRowVersion.Default);
			db.AddInParameter(da.InsertCommand, "@IsJobPlacer", DbType.Boolean, "IsJobPlacer", DataRowVersion.Default);
			db.AddInParameter(da.InsertCommand, "@Del", DbType.Boolean, "Del", DataRowVersion.Default);

			#endregion
			
			#region Parametros de UpdateCommand
			db.AddInParameter(da.UpdateCommand, "@UserTypeID", DbType.Int32, "UserTypeID", DataRowVersion.Default);
			db.AddInParameter(da.UpdateCommand, "@Name", DbType.String, "Name", DataRowVersion.Default);
			db.AddInParameter(da.UpdateCommand, "@IsBuyer", DbType.Boolean, "IsBuyer", DataRowVersion.Default);
			db.AddInParameter(da.UpdateCommand, "@IsAdPlacer", DbType.Boolean, "IsAdPlacer", DataRowVersion.Default);
			db.AddInParameter(da.UpdateCommand, "@IsJobPlacer", DbType.Boolean, "IsJobPlacer", DataRowVersion.Default);
			db.AddInParameter(da.UpdateCommand, "@Del", DbType.Boolean, "Del", DataRowVersion.Default);

			#endregion
			
			#region Parametros de DeleteCommand
			db.AddInParameter(da.DeleteCommand, "@UserTypeID", DbType.Int32, "UserTypeID", DataRowVersion.Default);

			#endregion

			db.UpdateDataSet(tabla.DataSet, tabla.TableName, da.InsertCommand, da.UpdateCommand, da.DeleteCommand, UpdateBehavior.Standard);
		}
		#endregion

		/// <summary>
		/// Populates a dataset with info from the database, based on the requested primary key.
		/// </summary>
		/// <param name="UserTypeID"></param>
		/// <returns>A DataSet containing the results of the query</returns>
		private DataSet LoadByPrimaryKey(int UserTypeID)
		{
			// Create the Database object, using the default database service. The
			// default database service is determined through configuration.
			Database db = DatabaseFactory.CreateDatabase();

			string sqlCommand = "daab_GetUserType";
			DbCommand dbCommandWrapper = db.GetStoredProcCommand(sqlCommand);

			// Add in parameters
			db.AddInParameter(dbCommandWrapper, "@UserTypeID", DbType.Int32, UserTypeID);

			// DataSet that will hold the returned results		
			// Note: connection closed by ExecuteDataSet method call 
			return db.ExecuteDataSet(dbCommandWrapper);
		}
	
		/// <summary>
		/// Populates current instance of the object with info from the database, based on the requested primary key.
		/// </summary>
		/// <param name="UserTypeID"></param>
		public virtual void Load(int UserTypeID)
		{
			// DataSet that will hold the returned results		
			DataSet ds = this.LoadByPrimaryKey(UserTypeID);
			
			// Load member variables from datarow
			DataRow row = ds.Tables[0].Rows[0];
			_UserTypeID = (int)row["UserTypeID"];
			_Name = row.IsNull("Name") ? string.Empty : (string)row["Name"];
			_IsBuyer = row.IsNull("IsBuyer") ? false : (bool)row["IsBuyer"];
			_IsAdPlacer = row.IsNull("IsAdPlacer") ? false : (bool)row["IsAdPlacer"];
			_IsJobPlacer = row.IsNull("IsJobPlacer") ? false : (bool)row["IsJobPlacer"];
			_Del = row.IsNull("Del") ? false : (bool)row["Del"];
		}

		/// <summary>
		/// Adds or updates information in the database depending on the primary key stored in the object instance.
		/// </summary>
		/// <returns>Returns True if saved successfully, False otherwise.</returns>
		public bool Save()
		{
			if (this.IsNew)
				return Insert();
			else
				return Update();
		}

		/// <summary>
		/// Inserts the current instance data into the database.
		/// </summary>
		/// <returns>Returns True if saved successfully, False otherwise.</returns>
		private bool Insert()
		{
			// Create the Database object, using the default database service. The
			// default database service is determined through configuration.
			Database db = DatabaseFactory.CreateDatabase();

			string sqlCommand = "daab_AddUserType";
			DbCommand dbCommandWrapper = db.GetStoredProcCommand(sqlCommand);

			// Add parameters
			db.AddOutParameter(dbCommandWrapper, "@UserTypeID", DbType.Int32, 4);
			db.AddInParameter(dbCommandWrapper, "@Name", DbType.String, SetNullValue((_Name == string.Empty), _Name));
			db.AddInParameter(dbCommandWrapper, "@IsBuyer", DbType.Boolean, SetNullValue((_IsBuyer == false), _IsBuyer));
			db.AddInParameter(dbCommandWrapper, "@IsAdPlacer", DbType.Boolean, SetNullValue((_IsAdPlacer == false), _IsAdPlacer));
			db.AddInParameter(dbCommandWrapper, "@IsJobPlacer", DbType.Boolean, SetNullValue((_IsJobPlacer == false), _IsJobPlacer));
            db.AddInParameter(dbCommandWrapper, "@Del", DbType.Boolean, SetNullValue((_Del == true), _Del));

			db.ExecuteNonQuery(dbCommandWrapper);
			
			// Save output parameter values
			object param;
			param = db.GetParameterValue(dbCommandWrapper, "@UserTypeID");
			if (param == DBNull.Value) return false;
			_UserTypeID = (int)param;
			
			return true;
		}

		/// <summary>
		/// Updates the current instance data in the database.
		/// </summary>
		/// <returns>Returns True if saved successfully, False otherwise.</returns>
		public bool Update()
		{
			// Create the Database object, using the default database service. The
			// default database service is determined through configuration.
			Database db = DatabaseFactory.CreateDatabase();

			string sqlCommand = "daab_UpdateUserType";
			DbCommand dbCommandWrapper = db.GetStoredProcCommand(sqlCommand);

			// Add parameters
			db.AddInParameter(dbCommandWrapper, "@UserTypeID", DbType.Int32, _UserTypeID);
			db.AddInParameter(dbCommandWrapper, "@Name", DbType.String, SetNullValue((_Name == string.Empty), _Name));
			db.AddInParameter(dbCommandWrapper, "@IsBuyer", DbType.Boolean, SetNullValue((_IsBuyer == false), _IsBuyer));
			db.AddInParameter(dbCommandWrapper, "@IsAdPlacer", DbType.Boolean, SetNullValue((_IsAdPlacer == false), _IsAdPlacer));
			db.AddInParameter(dbCommandWrapper, "@IsJobPlacer", DbType.Boolean, SetNullValue((_IsJobPlacer == false), _IsJobPlacer));
			db.AddInParameter(dbCommandWrapper, "@Del", DbType.Boolean, SetNullValue((_Del == false), _Del));

			try
			{
				db.ExecuteNonQuery(dbCommandWrapper);
				
				// Save output parameter values
				object param;
				param = db.GetParameterValue(dbCommandWrapper, "@UserTypeID");
				if (param == DBNull.Value) return false;
				_UserTypeID = (int)param;
				
				return true;
			}
			catch
			{
				return false;
			}
		}

		/// <summary>
		/// Removes info from the database, based on the requested primary key.
		/// </summary>
		/// <param name="UserTypeID"></param>
		public static void Remove(int UserTypeID)
		{
			// Create the Database object, using the default database service. The
			// default database service is determined through configuration.
			Database db = DatabaseFactory.CreateDatabase();

			string sqlCommand = "daab_DeleteUserType";
			DbCommand dbCommandWrapper = db.GetStoredProcCommand(sqlCommand);

			// Add primary keys to command wrapper.
			db.AddInParameter(dbCommandWrapper, "@UserTypeID", DbType.Int32, UserTypeID);

			db.ExecuteNonQuery(dbCommandWrapper);
		}
		
		/// <summary>
		/// Serializes the current instance data to an Xml string.
		/// </summary>
		/// <returns>A string containing the Xml representation of the object.</returns>
		virtual public string ToXml()
		{
			// DataSet that will hold the returned results		
			DataSet ds = this.LoadByPrimaryKey(_UserTypeID);
			StringWriter writer = new StringWriter(); 
			ds.WriteXml(writer); 
			return writer.ToString(); 
		}

		/// <summary>
		/// Utility function that returns a DBNull.Value if requested. The comparison is done inline
		/// in the Insert() and Update() functions.
		/// </summary>
		private object SetNullValue(bool isNullValue, object value)
		{
			if (isNullValue)
				return DBNull.Value;
			else
				return value;
		}
	}
}
