/*
'===============================================================================
'  Generated From - CSharp_DAAB_BusinessEntity.vbgen
' 
'  ** IMPORTANT  ** 
'  How to Generate your stored procedures:
' 
'  SQL      = SQL_DAAB_Net2_StoredProcs.vbgen
'  
'  This object is 'abstract' which means you need to inherit from it to be able
'  to instantiate it.  This is very easily done. You can override properties and
'  methods in your derived class, this allows you to regenerate this class at any
'  time and not worry about overwriting custom code. 
'
'  NEVER EDIT THIS FILE.
'
'  public class YourObject :  YourObjectBase
'  {
'
'  }
'
'===============================================================================
*/

// Generated by MyGeneration Version # (1.3.0.3)

using System;
using System.Data;
using System.Configuration;
using System.Collections;
using System.Collections.Specialized;
using System.Xml;
using System.IO;

using Microsoft.Practices.EnterpriseLibrary.Data;
using System.Data.Common;

namespace DL
{
	public abstract class UserBase
	{
		#region < VARIABLES >
		private int _UserID;
		private string _Name;
		private string _Username;
		private string _Password;
		private int _UserTypeID;
		private int _AccountID;
		private string _Email;
		private string _Website;
		private string _Telephone;
		private DateTime _CreatedOn;
		private DateTime _LastLogin;
		private int _UserStatusID;
		private bool _Del;
		private bool _isNew;
		#endregion
		
		#region < CONSTRUCTORES >
		protected UserBase()
		{
			_UserID = 0;
			_Name = string.Empty;
			_Username = string.Empty;
			_Password = string.Empty;
			_UserTypeID = 0;
			_AccountID = 0;
			_Email = string.Empty;
			_Website = string.Empty;
			_Telephone = string.Empty;
			_CreatedOn = DateTime.Parse("01/01/1900");
			_LastLogin = DateTime.Parse("01/01/1900");
			_UserStatusID = 0;
			_Del = false;
		}
		
		protected UserBase(int UserID) : this()
		{
			_UserID = UserID;
		}
	
		protected UserBase(int UserID, string Name, string Username, string Password, int UserTypeID, int AccountID, string Email, string Website, string Telephone, DateTime CreatedOn, DateTime LastLogin, int UserStatusID, bool Del) : this()
		{
			_UserID = UserID;
			_Name = Name;
			_Username = Username;
			_Password = Password;
			_UserTypeID = UserTypeID;
			_AccountID = AccountID;
			_Email = Email;
			_Website = Website;
			_Telephone = Telephone;
			_CreatedOn = CreatedOn;
			_LastLogin = LastLogin;
			_UserStatusID = UserStatusID;
			_Del = Del;
		}

		#endregion
		
		#region < Metodos para Obtención de Detalles >

		public static DataTable GetByUserStatus(int UserStatusID)
		{
			Database db = DatabaseFactory.CreateDatabase();
            string sqlCommand = "Select * From User Where UserStatusID = @UserStatusID";
            DbCommand dbCommandWrapper = db.GetSqlStringCommand(sqlCommand);
			db.AddInParameter(dbCommandWrapper, "@UserStatusID", DbType.Int32, UserStatusID);

			DataTable t = db.ExecuteDataSet(dbCommandWrapper).Tables[0];
			
			t.Columns["UserStatusID"].DefaultValue = UserStatusID;

            return t;
		}

		public static DataTable GetByUserType(int UserTypeID)
		{
			Database db = DatabaseFactory.CreateDatabase();
            string sqlCommand = "Select * From User Where UserTypeID = @UserTypeID";
            DbCommand dbCommandWrapper = db.GetSqlStringCommand(sqlCommand);
			db.AddInParameter(dbCommandWrapper, "@UserTypeID", DbType.Int32, UserTypeID);

			DataTable t = db.ExecuteDataSet(dbCommandWrapper).Tables[0];
			
			t.Columns["UserTypeID"].DefaultValue = UserTypeID;

            return t;
		}

		#endregion
		
		#region < PROPIEDADES >
		
		public int UserID
		{
			get	{ return _UserID; }
			set	{ _UserID = value; }
		}
		
		public string Name
		{
			get	{ return _Name; }
			set	{ _Name = value; }
		}
		
		public string Username
		{
			get	{ return _Username; }
			set	{ _Username = value; }
		}
		
		public string Password
		{
			get	{ return _Password; }
			set	{ _Password = value; }
		}
		
		public int UserTypeID
		{
			get	{ return _UserTypeID; }
			set	{ _UserTypeID = value; }
		}
		
		public int AccountID
		{
			get	{ return _AccountID; }
			set	{ _AccountID = value; }
		}
		
		public string Email
		{
			get	{ return _Email; }
			set	{ _Email = value; }
		}
		
		public string Website
		{
			get	{ return _Website; }
			set	{ _Website = value; }
		}
		
		public string Telephone
		{
			get	{ return _Telephone; }
			set	{ _Telephone = value; }
		}
		
		public DateTime CreatedOn
		{
			get	{ return _CreatedOn; }
			set	{ _CreatedOn = value; }
		}
		
		public DateTime LastLogin
		{
			get	{ return _LastLogin; }
			set	{ _LastLogin = value; }
		}
		
		public int UserStatusID
		{
			get	{ return _UserStatusID; }
			set	{ _UserStatusID = value; }
		}
		
		public bool Del
		{
			get	{ return _Del; }
			set	{ _Del = value; }
		}
		
		public bool IsNew
		{
			get 
			{ 
				_isNew = (_UserID == 0);
				return _isNew; 
			}
			set { _isNew = value; }
		}
		#endregion		

		#region Utilerias
		public static bool Existe(int UserID)
		{
			Database db = DatabaseFactory.CreateDatabase();
			string sqlCommand = "daab_ExistsUser";
			DbCommand dbCommandWrapper = db.GetStoredProcCommand(sqlCommand);

			// Add in parameters
			db.AddInParameter(dbCommandWrapper, "@UserID", DbType.Int32, UserID);

			// DataSet that will hold the returned results		
			// Note: connection closed by ExecuteDataSet method call 
			bool ret = false;
			int num = Convert.ToInt32(db.ExecuteScalar(dbCommandWrapper));
			ret = num > 0;
			return ret;
		}
		
		public static DataTable GetAllUser()
		{
			Database db = DatabaseFactory.CreateDatabase();

			string sqlCommand = "daab_GetAllUser";
			DbCommand dbCommandWrapper = db.GetStoredProcCommand(sqlCommand);
			DataTable ret = db.ExecuteDataSet(dbCommandWrapper).Tables[0];
			
            ret.PrimaryKey = new DataColumn[] { ret.Columns["UserID"] };
			
            return ret;
		}
		
		public static void SaveAll(DataTable tabla)
		{
			Database db = DatabaseFactory.CreateDatabase();
			DbDataAdapter da = db.GetDataAdapter();
			
			da.SelectCommand = db.GetStoredProcCommand("daab_GetAllUser");
            da.InsertCommand = db.GetStoredProcCommand("daab_AddUser");
            da.UpdateCommand = db.GetStoredProcCommand("daab_UpdateUser");
            da.DeleteCommand = db.GetStoredProcCommand("daab_DeleteUser");
			
			#region Parametros de InsertCommand
			db.AddOutParameter(da.InsertCommand, "@UserID", DbType.Int32, 4);
			db.AddInParameter(da.InsertCommand, "@Name", DbType.String, "Name", DataRowVersion.Default);
			db.AddInParameter(da.InsertCommand, "@Username", DbType.String, "Username", DataRowVersion.Default);
			db.AddInParameter(da.InsertCommand, "@Password", DbType.String, "Password", DataRowVersion.Default);
			db.AddInParameter(da.InsertCommand, "@UserTypeID", DbType.Int32, "UserTypeID", DataRowVersion.Default);
			db.AddInParameter(da.InsertCommand, "@AccountID", DbType.Int32, "AccountID", DataRowVersion.Default);
			db.AddInParameter(da.InsertCommand, "@Email", DbType.String, "Email", DataRowVersion.Default);
			db.AddInParameter(da.InsertCommand, "@Website", DbType.String, "Website", DataRowVersion.Default);
			db.AddInParameter(da.InsertCommand, "@Telephone", DbType.String, "Telephone", DataRowVersion.Default);
			db.AddInParameter(da.InsertCommand, "@CreatedOn", DbType.DateTime, "CreatedOn", DataRowVersion.Default);
			db.AddInParameter(da.InsertCommand, "@LastLogin", DbType.DateTime, "LastLogin", DataRowVersion.Default);
			db.AddInParameter(da.InsertCommand, "@UserStatusID", DbType.Int32, "UserStatusID", DataRowVersion.Default);
			db.AddInParameter(da.InsertCommand, "@Del", DbType.Boolean, "Del", DataRowVersion.Default);

			#endregion
			
			#region Parametros de UpdateCommand
			db.AddInParameter(da.UpdateCommand, "@UserID", DbType.Int32, "UserID", DataRowVersion.Default);
			db.AddInParameter(da.UpdateCommand, "@Name", DbType.String, "Name", DataRowVersion.Default);
			db.AddInParameter(da.UpdateCommand, "@Username", DbType.String, "Username", DataRowVersion.Default);
			db.AddInParameter(da.UpdateCommand, "@Password", DbType.String, "Password", DataRowVersion.Default);
			db.AddInParameter(da.UpdateCommand, "@UserTypeID", DbType.Int32, "UserTypeID", DataRowVersion.Default);
			db.AddInParameter(da.UpdateCommand, "@AccountID", DbType.Int32, "AccountID", DataRowVersion.Default);
			db.AddInParameter(da.UpdateCommand, "@Email", DbType.String, "Email", DataRowVersion.Default);
			db.AddInParameter(da.UpdateCommand, "@Website", DbType.String, "Website", DataRowVersion.Default);
			db.AddInParameter(da.UpdateCommand, "@Telephone", DbType.String, "Telephone", DataRowVersion.Default);
			db.AddInParameter(da.UpdateCommand, "@CreatedOn", DbType.DateTime, "CreatedOn", DataRowVersion.Default);
			db.AddInParameter(da.UpdateCommand, "@LastLogin", DbType.DateTime, "LastLogin", DataRowVersion.Default);
			db.AddInParameter(da.UpdateCommand, "@UserStatusID", DbType.Int32, "UserStatusID", DataRowVersion.Default);
			db.AddInParameter(da.UpdateCommand, "@Del", DbType.Boolean, "Del", DataRowVersion.Default);

			#endregion
			
			#region Parametros de DeleteCommand
			db.AddInParameter(da.DeleteCommand, "@UserID", DbType.Int32, "UserID", DataRowVersion.Default);

			#endregion

			db.UpdateDataSet(tabla.DataSet, tabla.TableName, da.InsertCommand, da.UpdateCommand, da.DeleteCommand, UpdateBehavior.Standard);
		}
		#endregion

		/// <summary>
		/// Populates a dataset with info from the database, based on the requested primary key.
		/// </summary>
		/// <param name="UserID"></param>
		/// <returns>A DataSet containing the results of the query</returns>
		private DataSet LoadByPrimaryKey(int UserID)
		{
			// Create the Database object, using the default database service. The
			// default database service is determined through configuration.
			Database db = DatabaseFactory.CreateDatabase();

			string sqlCommand = "daab_GetUser";
			DbCommand dbCommandWrapper = db.GetStoredProcCommand(sqlCommand);

			// Add in parameters
			db.AddInParameter(dbCommandWrapper, "@UserID", DbType.Int32, UserID);

			// DataSet that will hold the returned results		
			// Note: connection closed by ExecuteDataSet method call 
			return db.ExecuteDataSet(dbCommandWrapper);
		}
	
		/// <summary>
		/// Populates current instance of the object with info from the database, based on the requested primary key.
		/// </summary>
		/// <param name="UserID"></param>
		public virtual void Load(int UserID)
		{
			// DataSet that will hold the returned results		
			DataSet ds = this.LoadByPrimaryKey(UserID);
			
			// Load member variables from datarow
			DataRow row = ds.Tables[0].Rows[0];
			_UserID = (int)row["UserID"];
			_Name = row.IsNull("Name") ? string.Empty : (string)row["Name"];
			_Username = row.IsNull("Username") ? string.Empty : (string)row["Username"];
			_Password = row.IsNull("Password") ? string.Empty : (string)row["Password"];
			_UserTypeID = row.IsNull("UserTypeID") ? 0 : (int)row["UserTypeID"];
			_AccountID = row.IsNull("AccountID") ? 0 : (int)row["AccountID"];
			_Email = row.IsNull("Email") ? string.Empty : (string)row["Email"];
			_Website = row.IsNull("Website") ? string.Empty : (string)row["Website"];
			_Telephone = row.IsNull("Telephone") ? string.Empty : (string)row["Telephone"];
			_CreatedOn = row.IsNull("CreatedOn") ? DateTime.Parse("01/01/1900") : (DateTime)row["CreatedOn"];
			_LastLogin = row.IsNull("LastLogin") ? DateTime.Parse("01/01/1900") : (DateTime)row["LastLogin"];
			_UserStatusID = row.IsNull("UserStatusID") ? 0 : (int)row["UserStatusID"];
			_Del = row.IsNull("Del") ? false : (bool)row["Del"];
		}

		/// <summary>
		/// Adds or updates information in the database depending on the primary key stored in the object instance.
		/// </summary>
		/// <returns>Returns True if saved successfully, False otherwise.</returns>
		public bool Save()
		{
			if (this.IsNew)
				return Insert();
			else
				return Update();
		}

		/// <summary>
		/// Inserts the current instance data into the database.
		/// </summary>
		/// <returns>Returns True if saved successfully, False otherwise.</returns>
		private bool Insert()
		{
			// Create the Database object, using the default database service. The
			// default database service is determined through configuration.
			Database db = DatabaseFactory.CreateDatabase();

			string sqlCommand = "daab_AddUser";
			DbCommand dbCommandWrapper = db.GetStoredProcCommand(sqlCommand);

			// Add parameters
			db.AddOutParameter(dbCommandWrapper, "@UserID", DbType.Int32, 4);
			db.AddInParameter(dbCommandWrapper, "@Name", DbType.String, SetNullValue((_Name == string.Empty), _Name));
			db.AddInParameter(dbCommandWrapper, "@Username", DbType.String, SetNullValue((_Username == string.Empty), _Username));
			db.AddInParameter(dbCommandWrapper, "@Password", DbType.String, SetNullValue((_Password == string.Empty), _Password));
			db.AddInParameter(dbCommandWrapper, "@UserTypeID", DbType.Int32, SetNullValue((_UserTypeID == 0), _UserTypeID));
			db.AddInParameter(dbCommandWrapper, "@AccountID", DbType.Int32, SetNullValue((_AccountID == 0), _AccountID));
			db.AddInParameter(dbCommandWrapper, "@Email", DbType.String, SetNullValue((_Email == string.Empty), _Email));
			db.AddInParameter(dbCommandWrapper, "@Website", DbType.String, SetNullValue((_Website == string.Empty), _Website));
			db.AddInParameter(dbCommandWrapper, "@Telephone", DbType.String, SetNullValue((_Telephone == string.Empty), _Telephone));
			db.AddInParameter(dbCommandWrapper, "@CreatedOn", DbType.DateTime, SetNullValue((_CreatedOn == DateTime.Parse("01/01/1900")), _CreatedOn));
			db.AddInParameter(dbCommandWrapper, "@LastLogin", DbType.DateTime, SetNullValue((_LastLogin == DateTime.Parse("01/01/1900")), _LastLogin));
			db.AddInParameter(dbCommandWrapper, "@UserStatusID", DbType.Int32, SetNullValue((_UserStatusID == 0), _UserStatusID));
			db.AddInParameter(dbCommandWrapper, "@Del", DbType.Boolean, SetNullValue((_Del == false), _Del));

			db.ExecuteNonQuery(dbCommandWrapper);
			
			// Save output parameter values
			object param;
			param = db.GetParameterValue(dbCommandWrapper, "@UserID");
			if (param == DBNull.Value) return false;
			_UserID = (int)param;
			
			return true;
		}

		/// <summary>
		/// Updates the current instance data in the database.
		/// </summary>
		/// <returns>Returns True if saved successfully, False otherwise.</returns>
		public bool Update()
		{
			// Create the Database object, using the default database service. The
			// default database service is determined through configuration.
			Database db = DatabaseFactory.CreateDatabase();

			string sqlCommand = "daab_UpdateUser";
			DbCommand dbCommandWrapper = db.GetStoredProcCommand(sqlCommand);

			// Add parameters
			db.AddInParameter(dbCommandWrapper, "@UserID", DbType.Int32, _UserID);
			db.AddInParameter(dbCommandWrapper, "@Name", DbType.String, SetNullValue((_Name == string.Empty), _Name));
			db.AddInParameter(dbCommandWrapper, "@Username", DbType.String, SetNullValue((_Username == string.Empty), _Username));
			db.AddInParameter(dbCommandWrapper, "@Password", DbType.String, SetNullValue((_Password == string.Empty), _Password));
			db.AddInParameter(dbCommandWrapper, "@UserTypeID", DbType.Int32, SetNullValue((_UserTypeID == 0), _UserTypeID));
			db.AddInParameter(dbCommandWrapper, "@AccountID", DbType.Int32, SetNullValue((_AccountID == 0), _AccountID));
			db.AddInParameter(dbCommandWrapper, "@Email", DbType.String, SetNullValue((_Email == string.Empty), _Email));
			db.AddInParameter(dbCommandWrapper, "@Website", DbType.String, SetNullValue((_Website == string.Empty), _Website));
			db.AddInParameter(dbCommandWrapper, "@Telephone", DbType.String, SetNullValue((_Telephone == string.Empty), _Telephone));
			db.AddInParameter(dbCommandWrapper, "@CreatedOn", DbType.DateTime, SetNullValue((_CreatedOn == DateTime.Parse("01/01/1900")), _CreatedOn));
			db.AddInParameter(dbCommandWrapper, "@LastLogin", DbType.DateTime, SetNullValue((_LastLogin == DateTime.Parse("01/01/1900")), _LastLogin));
			db.AddInParameter(dbCommandWrapper, "@UserStatusID", DbType.Int32, SetNullValue((_UserStatusID == 0), _UserStatusID));
			db.AddInParameter(dbCommandWrapper, "@Del", DbType.Boolean, SetNullValue((_Del == false), _Del));

			try
			{
				db.ExecuteNonQuery(dbCommandWrapper);
				
				// Save output parameter values
				object param;
				param = db.GetParameterValue(dbCommandWrapper, "@UserID");
				if (param == DBNull.Value) return false;
				_UserID = (int)param;
				
				return true;
			}
			catch
			{
				return false;
			}
		}

		/// <summary>
		/// Removes info from the database, based on the requested primary key.
		/// </summary>
		/// <param name="UserID"></param>
		public static void Remove(int UserID)
		{
			// Create the Database object, using the default database service. The
			// default database service is determined through configuration.
			Database db = DatabaseFactory.CreateDatabase();

			string sqlCommand = "daab_DeleteUser";
			DbCommand dbCommandWrapper = db.GetStoredProcCommand(sqlCommand);

			// Add primary keys to command wrapper.
			db.AddInParameter(dbCommandWrapper, "@UserID", DbType.Int32, UserID);

			db.ExecuteNonQuery(dbCommandWrapper);
		}
		
		/// <summary>
		/// Serializes the current instance data to an Xml string.
		/// </summary>
		/// <returns>A string containing the Xml representation of the object.</returns>
		virtual public string ToXml()
		{
			// DataSet that will hold the returned results		
			DataSet ds = this.LoadByPrimaryKey(_UserID);
			StringWriter writer = new StringWriter(); 
			ds.WriteXml(writer); 
			return writer.ToString(); 
		}

		/// <summary>
		/// Utility function that returns a DBNull.Value if requested. The comparison is done inline
		/// in the Insert() and Update() functions.
		/// </summary>
		private object SetNullValue(bool isNullValue, object value)
		{
			if (isNullValue)
				return DBNull.Value;
			else
				return value;
		}
	}
}
